// ============================================================================
// Boost Software License - Version 1.0 - August 17th, 2003

// Copyright (c) 2026 Teo Boutin

// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:

// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// ============================================================================
// bijection.h  —  emap::bijection<E1, E2>
// A total_map between two same-sized enums whose stored values are proven
// pairwise distinct — a compile-time bijection, invertible without re-proof.
// Requires C++20.
// ----------------------------------------------------------------------------
//
// WHAT IT IS
//   emap::bijection<E1, E2> IS a total_map<E1, E2> (public inheritance, and
//   meant that way: everything proven about the base holds here) that has
//   additionally proven, at construction, that no two rows carry the same E2
//   value. The header also demands enum_count_v<E1> == enum_count_v<E2> — a
//   static_assert, because it is a property of the TYPES, not of any rows.
//   Between finite sets of equal size, total + injective implies surjective,
//   so the instance is a proven BIJECTION and no separate surjectivity check
//   ever runs.
//
// INTENDED USE
//   Two enums that are one set with two spellings: a wire protocol's codes
//   and the internal enum, a save-format id and the live id, scan codes and
//   logical keys.
//
//       enum class Port { A, B, C, Count };
//       enum class Pin  { P0, P1, P2, Count };
//
//       constexpr emap::bijection wires{
//           emap::entry{Port::A, Pin::P2},
//           emap::entry{Port::B, Pin::P0},
//           emap::entry{Port::C, Pin::P1},  // repeat a Pin -> compile error
//       };
//       static_assert(wires[Port::A] == Pin::P2);            // inherited
//       static_assert(wires.inverse()[Pin::P2] == Port::A);  // licensed
//
//   E1 == E2 is legal and useful: bijection<E, E> is a proven PERMUTATION of
//   one enum (a successor cycle, a remapping), and inverse() simply returns
//   the same type.
//
// CONSTRUCTION — always through a proven table
//   Mirrors keyed_map exactly. The primary constructor PROMOTES an already-
//   proven total_map<E1, E2>; consteval and IMPLICIT, deliberately: an API
//   taking bijection can be handed a total_map and the missing proof is
//   demanded — at compile time — right at the call site. Row / array
//   authoring forms are sugar that builds the total_map first, so key
//   diagnostics are total_map's own, verbatim; what this header adds is the
//   value-distinctness check, run on the proven table before the base is
//   initialized. There is deliberately NO from(): the promote path composes —
//   emap::bijection<E1, E2>{emap::total_map<E1, E2>::from(fn)}. And there is
//   no path FROM emap::mutable_total_map, as for every refinement: a table
//   that can drift is exactly the object this proof no longer covers.
//
// WHAT THE PROOF LICENSES — inverse(), and its single-slot form inverse_at()
//   inverse() returns bijection<E2, E1>: the whole map read the other way,
//   O(1) in both directions once materialized. consteval, like every
//   construction path — materializing a map IS construction. It does NOT
//   re-run any check: the inverse of a proven bijection is proven by the
//   same evidence, so inverse() enters through a private tagged constructor
//   (see the door below for the reasoning). Round trip:
//   b.inverse()[b[e]] == e for every key, and inverse().inverse() compares
//   equal to b.
//
//   inverse_at(E2) returns the ONE key mapping to that value, without
//   materializing the inverse map — constexpr, because runtime lookup of a
//   compile-time-proven table is the point. It returns E1 BY VALUE, no
//   pointer: unlike keyed_map::find, nothing here is partial — bijectivity
//   makes the inverse total. O(N) scan, nothing at enumerator counts. Its
//   VALUE argument is checked like operator[]'s key: debug assert only — a
//   forged E2 (a cast, or a Count sentinel used as a live value) asserts
//   under !NDEBUG and returns a well-defined but WRONG key in release.
//
// DIAGNOSTICS
//   * A repeated E2 value: `enum value repeated`, with the two colliding
//     slots as TEMPLATE ARGUMENTS of the error function (measured, not
//     stylistic — see the emap::error block in keyed_map.h; same unrolled-
//     check consequence). Distinct from total_map's `duplicate enum key`:
//     here the VALUES are enumerators of E2, and with equal counts a value
//     hit twice means another E2 value is necessarily missed.
//   * Unequal counts: a static_assert containing `enum counts differ`. NOTE
//     THE EDGE this implies: a class-scope static_assert fires at implicit
//     instantiation of the TYPE, outside any immediate context, so
//     emap::bijective on rows between count-mismatched enums is a HARD
//     ERROR, not `false` — the same documented behavior as buildable's NTTP
//     edges and total_map's own E/V asserts. bijective answers for tables
//     between count-compatible enums; between count-incompatible enums
//     there is nothing to ask.
//   * Key-side failures (missing enumerator, duplicate key, out of range):
//     total_map's own messages, verbatim, from the delegated construction.
//
// REQUIREMENTS & GUARANTEES
//   total_map<E1, E2>'s, exactly (contiguity and enum_count discovery for
//   E1, rejection of bad row sets — delegated), plus:
//   * E2 must itself be an enum with a discoverable count (same three-way
//     customization as E1's; see enum_count in total_map.h), and
//     enum_count_v<E1> == enum_count_v<E2>.
//   * Whether a row set would be accepted is again a compile-time predicate,
//     emap::bijective<Arr> / emap::bijective<&Arr>, mirroring
//     emap::buildable's two passing forms and restrictions. It answers for
//     the WHOLE construction, so bijective subsumes buildable.
// ============================================================================

#ifndef BIJECTION_INCLUDED
#define BIJECTION_INCLUDED

// The quote form, deliberately: it resolves relative to THIS file first, so
// the headers can be copied into a project as one emap/ directory and work
// with no include-path setup — the same no-build-system install path
// total_map.h supports alone. Version macros live in total_map.h; one
// library, one version.
#include "total_map.h"

#include <array>
#include <cassert>
#include <concepts>
#include <cstddef>
#include <type_traits>
#include <utility>

namespace emap
{

// A rejected table is reported the same way total_map's are — a call to a
// declared-but-undefined function is not a constant expression — and for the
// same -fno-exceptions reasons (see the emap::error block in total_map.h).
// The message literal starts on the call's own line, as clang's caret echo
// requires; the two colliding SLOTS ride the template arguments, for the
// measured reasons documented on keyed_map.h's emap::error block. Slots are
// enum order, so slot I's key is key_at(I).
namespace error
{
template <std::size_t FirstSlot, std::size_t SecondSlot>
void enum_value_repeated(const char* why);
} // namespace error

template <class E1, class E2> class bijection : public total_map<E1, E2>
{
    // Mirrors total_map's guards so a bad E1/E2 is reported against the type
    // actually named in the source; the base re-checks E1 behind these, but
    // by then the diagnostic would blame the delegation target. E2 gets the
    // full treatment here because for the BASE it is only a value type — the
    // enum-ness and count of E2 are this refinement's own requirements.
    static_assert(std::is_enum_v<E1>, "emap::bijection: E1 must be an enum type.");
    static_assert(std::is_enum_v<E2>,
        "emap::bijection: E2 must be an enum type — the VALUES of a bijection are "
        "enumerators. For a map to non-enum values, use total_map or keyed_map.");
    static_assert(has_enum_count<E1>,
        "emap::bijection: could not determine the number of enumerators of E1. Add a "
        "trailing sentinel enumerator (`Count` by default), specialize "
        "emap::enum_count<E1>::value, or claim E1 with an emap::enum_count_policy<E1>.");
    static_assert(has_enum_count<E2>,
        "emap::bijection: could not determine the number of enumerators of E2. Add a "
        "trailing sentinel enumerator (`Count` by default), specialize "
        "emap::enum_count<E2>::value, or claim E2 with an emap::enum_count_policy<E2>.");

    // A property of the TYPES, not of any rows — which is why it is a
    // static_assert and not an emap::error call. Consequence (documented in
    // DIAGNOSTICS above): emap::bijective hard-errors, rather than answering
    // false, for rows between count-mismatched enums.
    static_assert(enum_count_v<E1> == enum_count_v<E2>,
        "emap::bijection: enum counts differ. A total injective map between finite "
        "sets exists only at equal sizes, so no bijection between these enums can "
        "exist. If either count surprises you, check the sentinel it was read from "
        "(see enum_count in total_map.h).");

    using base = total_map<E1, E2>;

    // --- the value-distinctness check: pairwise over the PROVEN table ---
    // A deliberate ~20-line twin of keyed_map's check_against_earlier /
    // check_all (with the identity projection over V = E2, and bijection's
    // own diagnostic). NOT factored into a shared detail:: helper: the shape
    // is pinned by the measured template-argument constraint both twins
    // document, so they cannot drift apart in substance, and keeping it
    // local keeps this header depending on total_map.h alone.
    static consteval bool values_equal(const base& tm, std::size_t a, std::size_t b)
    {
        return tm[base::key_at(a)] == tm[base::key_at(b)];
    }

    template <std::size_t FirstSlot, std::size_t SecondSlot> static consteval void report()
    {
        error::enum_value_repeated<FirstSlot, SecondSlot>("emap::bijection: enum value repeated. Two rows map to the same E2 "
            "enumerator — and with equal counts, a value hit twice means some other "
            "E2 enumerator is never hit at all, so the table cannot be a bijection. "
            "The template arguments name the colliding slots, in enum order: "
            "key_at(slot) is the row.");
    }

    // Slot J against every earlier slot; then every J. Empty comma folds
    // (J == 0, and N == 1 overall) are well-formed no-ops.
    template <std::size_t J, std::size_t... Is>
    static consteval void check_against_earlier(const base& tm, std::index_sequence<Is...>)
    {
        ((values_equal(tm, Is, J) ? report<Is, J>() : void()), ...);
    }

    template <std::size_t... Js>
    static consteval void check_all(const base& tm, std::index_sequence<Js...>)
    {
        (check_against_earlier<Js>(tm, std::make_index_sequence<Js>{}), ...);
    }

    // Returns its argument so the promoting constructor can initialize the
    // base from the checked table in one expression.
    static consteval base check(const base& tm)
    {
        check_all(tm, std::make_index_sequence<base::size()>{});
        return tm;
    }

    // --- the tagged door: check-free construction of a PROVEN inverse ---
    // Every other constructor proves; this one is HANDED a proof. The
    // inverse of a proven bijection is proven by the same evidence — one set
    // of N distinct pairs, read the other way — so re-running the check here
    // would not add safety, it would state that the proof is doubted. The
    // door stays invisible from outside: tag and constructor are private,
    // reachable only through the friendship below, so the public invariant —
    // every reachable constructor proves — survives.
    //
    // The BASE is not opened at all: total_map::from is already the
    // check-free totality path (a function cannot lie), and the callable
    // below is total over E1 by its type. What this door skips is only the
    // value-distinctness RE-check. O(N^2) consteval work (N inverse_at
    // scans) — nothing at enumerator counts.
    struct proven_inverse_t {};

    // ALL specializations are friends, deliberately: bijection<E2, E1> must
    // reach this constructor from ITS inverse(), the one-line spelling is
    // fully portable where one-off mutual friendship risks toolchain
    // divergence, and the door it widens is still private. E1 == E2 makes
    // this self-friendship — harmless.
    template <class, class> friend class bijection;

    consteval bijection(proven_inverse_t, const bijection<E2, E1>& forward)
        : base(base::from([&forward](E1 key) { return forward.inverse_at(key); }))
    {
    }

  public:
    // PROMOTE — the primary constructor: an already-proven total_map, with
    // the value-distinctness check run before the base is initialized.
    // consteval and IMPLICIT, deliberately (see CONSTRUCTION above).
    consteval bijection(const base& tm) : base(check(tm)) {}

    // Authoring sugar. Each form builds the total_map FIRST and promotes it,
    // so key validation and its diagnostics stay in exactly one place —
    // total_map — and the value check in exactly one other: check(), above.
    template <std::size_t M>
    consteval bijection(const std::array<entry<E1, E2>, M>& in) : bijection(base(in))
    {
    }

    template <std::same_as<entry<E1, E2>>... Rows>
    consteval bijection(Rows... rows) : bijection(base(rows...))
    {
    }

    // SINGLE-SLOT inverse lookup — the proof's cheap half, without
    // materializing the whole inverse map. constexpr, not consteval: runtime
    // lookup of a compile-time-proven table is the point. Returns E1 BY
    // VALUE — bijectivity makes the inverse TOTAL, so unlike keyed_map::find
    // there is no partial case to be honest about. O(N) scan, nothing at
    // enumerator counts.
    //
    // The debug assert mirrors operator[]'s: a forged E2 — a cast, or a
    // Count sentinel used as a live value — asserts under !NDEBUG; in
    // release the scan returns a well-defined but WRONG key for a forged
    // value, which is an array's contract stated for the value side.
    constexpr E1 inverse_at(E2 v) const
    {
        assert(static_cast<std::size_t>(v) < base::size() &&
               "emap::bijection: value out of range (a sentinel used as a live value?)");
        for (std::size_t i = 0; i + 1 < base::size(); ++i) {
            if ((*this)[base::key_at(i)] == v) {
                return base::key_at(i);
            }
        }
        // Not a guess: the proof says v IS some slot's value, and no earlier
        // slot matched, so it is the last one's. (This is also what lets the
        // function end without a control path the compiler must warn about.)
        return base::key_at(base::size() - 1);
    }

    // THE OPERATION THE PROOF LICENSES: the whole map, read the other way,
    // O(1) in both directions once materialized. consteval, like every
    // construction path — materializing a map IS construction. Enters
    // bijection<E2, E1> through its private tagged door (above): no check
    // re-runs, because none could fail.
    consteval bijection<E2, E1> inverse() const
    {
        using inverse_type = bijection<E2, E1>;
        return inverse_type(typename inverse_type::proven_inverse_t{}, *this);
    }
};

// Deduction guides, mirroring the base's own — both enums come off the rows
// (or the promoted table), so unlike keyed_map nothing is left to name.
template <class E1, class E2> bijection(const total_map<E1, E2>&) -> bijection<E1, E2>;
template <class E1, class E2, std::size_t M>
bijection(const std::array<entry<E1, E2>, M>&) -> bijection<E1, E2>;
template <class E1, class E2, class... Rest>
bijection(entry<E1, E2>, Rest...) -> bijection<E1, E2>;

} // namespace emap

// ============================================================================
// SELF-TESTS
// Same contract as total_map.h's: opt-in via TOTAL_MAP_SELFTEST, compile-time
// only, a clean compile is the pass. Self-contained — fresh type names, so it
// holds even in a TU where the other headers' selftests are also compiled
// (tests/selftest_snapshot.cpp is exactly such a TU). See
// tests/selftest_bijection.cpp for the three-line driver.
// ============================================================================
#ifdef TOTAL_MAP_SELFTEST
namespace emap::selftest
{

enum class Port { A, B, C, Count };
enum class Pin { P0, P1, P2, Count };

// --- CTAD from rows: both enums come off the entries ---
constexpr emap::bijection kWires{
    entry{Port::A, Pin::P2}, entry{Port::B, Pin::P0}, entry{Port::C, Pin::P1}};
static_assert(std::is_same_v<decltype(kWires), const emap::bijection<Port, Pin>>);

// the base's contract is inherited intact: total lookup, size, key recovery
static_assert(kWires[Port::A] == Pin::P2);
static_assert(kWires.size() == 3);
static_assert(kWires.key_at(2) == Port::C);

// --- IS-A total_map: the proof only ever ADDS ---
static_assert(std::is_base_of_v<emap::total_map<Port, Pin>, decltype(kWires)>);
static_assert(std::convertible_to<const emap::bijection<Port, Pin>&,
                                  const emap::total_map<Port, Pin>&>);
// the all_unique predicate agrees with the proof the type already carries
static_assert(emap::all_unique(kWires));
// equality reaches through the base, in both directions
constexpr emap::total_map kWiresPlain{
    entry{Port::B, Pin::P0}, entry{Port::C, Pin::P1}, entry{Port::A, Pin::P2}};
static_assert(kWires == kWiresPlain);
static_assert(kWiresPlain == kWires);

// --- promote: an already-proven table, CTAD from the primary constructor ---
constexpr emap::bijection kWiresPromoted = kWiresPlain;
static_assert(std::is_same_v<decltype(kWiresPromoted), const emap::bijection<Port, Pin>>);
static_assert(kWiresPromoted == kWires);

// --- the array authoring form ---
constexpr emap::bijection kWiresFromArray{std::array{
    entry{Port::A, Pin::P2}, entry{Port::B, Pin::P0}, entry{Port::C, Pin::P1}}};
static_assert(kWiresFromArray == kWires);

// authoring through from(): the promote path composes, no from() of its own
constexpr emap::bijection<Port, Pin> kWiresFromFn{emap::total_map<Port, Pin>::from(
    [](Port p) { return static_cast<Pin>((static_cast<int>(p) + 1) % 3); })};
static_assert(kWiresFromFn[Port::A] == Pin::P1);

// --- inverse_at: the single-slot inverse, licensed by the proof ---
// Total, so by value — no pointer: bijectivity means every E2 value has
// exactly one key, and the signature says so.
static_assert(kWires.inverse_at(Pin::P0) == Port::B);
static_assert(kWires.inverse_at(Pin::P1) == Port::C);
static_assert(kWires.inverse_at(Pin::P2) == Port::A);

// --- inverse(): the licensed operation — round trip over every key ---
constexpr auto kUnwires = kWires.inverse();
static_assert(std::is_same_v<decltype(kUnwires), const emap::bijection<Pin, Port>>);
static_assert([] {
    for (Port p : decltype(kWires)::keys()) {
        if (kUnwires[kWires[p]] != p) {
            return false;
        }
    }
    return true;
}());
static_assert([] {
    for (Pin q : decltype(kUnwires)::keys()) {
        if (kWires[kUnwires[q]] != q) {
            return false;
        }
    }
    return true;
}());

// inverse().inverse(): type and value identity
static_assert(std::is_same_v<decltype(kUnwires.inverse()), emap::bijection<Port, Pin>>);
static_assert(kUnwires.inverse() == kWires);

// the materialized inverse and the single-slot form agree
static_assert(kUnwires[Pin::P0] == kWires.inverse_at(Pin::P0));

// --- a permutation: E1 == E2 is a legal, useful bijection ---
enum class Ring { R0, R1, R2, Count };
constexpr emap::bijection kSucc{
    entry{Ring::R0, Ring::R1}, entry{Ring::R1, Ring::R2}, entry{Ring::R2, Ring::R0}};
static_assert(std::is_same_v<decltype(kSucc), const emap::bijection<Ring, Ring>>);
static_assert(kSucc.inverse_at(Ring::R1) == Ring::R0); // the predecessor
constexpr auto kPred = kSucc.inverse();
static_assert(kPred[Ring::R0] == Ring::R2);
static_assert(kPred.inverse() == kSucc);

// --- immutable, like the base: proofs must outlive their statement ---
static_assert(!std::is_copy_assignable_v<emap::bijection<Port, Pin>>);
static_assert(!std::is_move_assignable_v<emap::bijection<Port, Pin>>);

} // namespace emap::selftest
#endif // TOTAL_MAP_SELFTEST

#endif // BIJECTION_INCLUDED
