// ============================================================================
// Boost Software License - Version 1.0 - August 17th, 2003

// Copyright (c) 2026 Teo Boutin

// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:

// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// ============================================================================
// keyed_map.h  —  emap::keyed_map<E, V, Proj>
// A total_map whose values are proven distinct under a projection — the
// type-level carrier of an emap::all_unique proof. Requires C++20.
// ----------------------------------------------------------------------------
//
// WHAT IT IS
//   emap::keyed_map<E, V, Proj> IS a total_map<E, V> (public inheritance, and
//   meant that way: everything proven about the base holds here) that has
//   additionally proven, at construction, that Proj maps no two of its values
//   to equal results. It is the TYPE-LEVEL form of the emap::all_unique
//   predicate: where `static_assert(emap::all_unique(m, proj))` states the
//   proof about one table, keyed_map<E, V, Proj> demands it of every instance
//   — a function signature taking keyed_map has the proof by type, with
//   nothing to re-assert.
//
//   The projected result is the value's ID — its identity within the table: a
//   wire code, a stringId, a config name. (NOT "key": in this library a key is
//   an enumerator of E, validated and dropped at construction. The two run in
//   opposite directions — the key picks the value; the id is derived FROM the
//   value.) Proven-distinct ids license the one operation total_map cannot
//   have: LOOKUP BY ID, find(), whose answer is well-defined precisely
//   because at most one value can match.
//
// INTENDED USE
//   Tables that are read in both directions: enum -> value stays the O(1)
//   inherited operator[], and id -> value becomes possible because collisions
//   were ruled out at compile time.
//
//       enum class Color { Red, Green, Blue, Count };
//       struct Style { int wireCode; int thickness; };
//
//       constexpr emap::keyed_map<Color, Style, &Style::wireCode> styles{
//           emap::entry{Color::Red,   Style{7,  1}},
//           emap::entry{Color::Green, Style{9,  2}},
//           emap::entry{Color::Blue,  Style{12, 3}},  // a duplicate wireCode
//       };                                            // -> compile error
//
//       static_assert(styles.find(9)->thickness == 2);   // hit
//       static_assert(styles.find(8) == nullptr);        // miss
//
//   Proj is a NON-TYPE template parameter — part of the TYPE, because the
//   proof is relative to it. It takes the same two forms all_unique accepts:
//   a pointer to data member (&Style::wireCode), or a captureless callable —
//   as of C++20 a lambda can be written directly in the argument list:
//
//       emap::keyed_map<Color, Style,
//           [](const Style& s) { return std::string_view{s.name}; }>
//
//   Omitted, Proj defaults to emap::identity_projection: the values THEMSELVES
//   are the ids, and the table is proven duplicate-free —
//   `emap::keyed_map codes{...}` (CTAD, like total_map's) for a code -> code
//   check, or scalar tables looked up from either end.
//
//   STRING-LIKE IDS: project to std::string_view (include it yourself), so id
//   equality means CONTENT — for the proof at construction AND for every later
//   find(). A raw `const char*` projection compares ADDRESSES. At construction,
//   constant evaluation makes that loud rather than wrong, in the
//   compiler-divergent ways all_unique documents; but find() also runs at RUN
//   TIME, where an address comparison is quietly legal and quietly meaningless.
//   The string_view projection is both the portable form and the one that says
//   what you mean.
//
// CONSTRUCTION — always through a proven table
//   Like mutable_total_map, this header contains no KEY validation at all: the
//   primary constructor PROMOTES an already-proven total_map, and the row /
//   array authoring forms are sugar that builds the total_map first. Key
//   diagnostics are therefore total_map's own, verbatim. What this header adds
//   is the ID check, run on the proven table before the base is initialized.
//
//   The promoting constructor is consteval and IMPLICIT, deliberately:
//   `emap::keyed_map<E, V, P> k = provenTable;` is the intended spelling, and
//   an implicit consteval conversion means an API taking keyed_map can be
//   handed a total_map and the missing proof is demanded — at compile time —
//   right at the call site. There is no runtime path to a keyed_map, so the
//   conversion can never smuggle an unproven table.
//
//   There is deliberately NO from(fn): the promote path already composes —
//   `emap::keyed_map<E, V, P> k{emap::total_map<E, V>::from(fn)};` — and a
//   second spelling of the same construction would be surface without
//   capability. For the same reason there is no mutable sibling and no path
//   FROM emap::mutable_total_map: a table that can drift is exactly the object
//   this type's proof no longer covers (see all_unique's block in
//   total_map.h). Prove the frozen baseline; a live table cannot be keyed.
//
// WHAT THE PROOF LICENSES — find(), and only find()
//   find(id) returns a pointer to THE value whose projection equals id, or
//   nullptr. A pointer, not a reference: id -> value is the one PARTIAL lookup
//   in this library — nothing proves an arbitrary id is present, only that a
//   present id is unambiguous — and the signature says so. (Contrast inherited
//   operator[]: totality was proven, so it answers unconditionally.) The
//   pointer is const: values are immutable, as on any total_map, which is what
//   makes the id proof durable for the instance's whole lifetime.
//
//   find() is constexpr, not consteval — runtime lookup of a compile-time-
//   proven table is the point. O(N) scan, which is nothing at enumerator
//   counts; a sorted index would buy O(log N) at the price of real machinery,
//   and can arrive later without changing this API.
//
//   The value's ENUM is deliberately not returned — it is already recoverable
//   in O(1) through the inherited API, because storage is positional:
//
//       const Style* s = styles.find(9);
//       Color c = styles.key_at(static_cast<std::size_t>(s - styles.data()));
//
//   transform() is inherited and returns a plain total_map<E, U> — CORRECT,
//   not an omission: mapping the values gives no reason their projections
//   stay distinct, so the proof is dropped with the type. Re-promote the
//   result if the new table should re-prove it.
//
// DIAGNOSTICS — two errors, because the fixes differ
//   * Under the DEFAULT identity projection, a collision means two rows carry
//     equal VALUES: `duplicate value`. The table is wrong; fix the rows.
//   * Under a REAL projection, the colliding rows are usually legitimately
//     distinct — it is the CHOICE OF Proj that failed to tell them apart:
//     `values collide under projection`. Question the projection before the
//     rows.
//   Both errors carry the two colliding slots as TEMPLATE ARGUMENTS — e.g.
//   `values_collide_under_projection<0, 2>` — so the offending rows are named
//   in the diagnostic text itself, no bisecting the table: slot's key is
//   key_at(slot), in enum order. Template arguments rather than runtime ones
//   is a measured choice, not a stylistic one; see the emap::error block
//   below.
//
// REQUIREMENTS & GUARANTEES
//   total_map's, exactly (same enum contiguity and enum_count discovery, same
//   V requirements, same rejection of bad row sets — delegated), plus:
//   * Proj must be a valid non-type template parameter (a data member pointer
//     and a captureless lambda both are), invocable on const V&, and its
//     result equality-comparable — the same bar all_unique sets, checked with
//     a friendly static_assert.
//   * Whether a table would be accepted is again a compile-time predicate:
//     emap::keyable<Arr, Proj> / emap::keyable<&Arr, Proj>, mirroring
//     emap::buildable's two passing forms and restrictions (see its block in
//     total_map.h). It answers for the WHOLE construction — a table that
//     fails total_map's own key checks is keyable == false too, so
//     keyable subsumes buildable.
// ============================================================================

#ifndef KEYED_MAP_INCLUDED
#define KEYED_MAP_INCLUDED

// The quote form, deliberately: it resolves relative to THIS file first, so
// the headers can be copied into a project as one emap/ directory and work
// with no include-path setup — the same no-build-system install path
// total_map.h supports alone. Version macros live in total_map.h; one
// library, one version.
#include "total_map.h"

#include <array>
#include <concepts>
#include <cstddef>
#include <type_traits>
#include <utility>

namespace emap
{

// The default projection: the value IS its own id. A named, empty, structural
// type — not std::identity — for two reasons: std::identity lives in
// <functional>, which this library deliberately does not buy (see
// detail::project in total_map.h), and the DEFAULTED projection is what
// selects the `duplicate value` diagnostic over the projection one, so it
// must be a type this header can recognize by name.
struct identity_projection {
    template <class T> constexpr T&& operator()(T&& t) const noexcept
    {
        return static_cast<T&&>(t);
    }
};

// The id a projection derives from a value: Proj's result, decayed to a value
// type — what find() takes and id_type names. Deduction inside
// detail::project handles a const-qualified Proj (a class-type NTTP denotes a
// const object).
namespace detail
{
template <auto Proj, class V>
using projected_id_t = std::remove_cvref_t<decltype(detail::project(
    std::declval<decltype(Proj)&>(), std::declval<const V&>()))>;
} // namespace detail

// A rejected table is reported the same way total_map's are — a call to a
// declared-but-undefined function is not a constant expression — and for the
// same -fno-exceptions reasons (see the emap::error block in total_map.h).
// The message literal starts on the call's own line, as clang's caret echo
// requires.
//
// The two colliding SLOTS ride the function's TEMPLATE ARGUMENTS, not runtime
// arguments — measured, not assumed: g++ 13.3's constant-evaluation notes
// echo the failing call's source line but do NOT print evaluated argument
// values, so `(..., j, i)` named nothing. Template arguments are part of the
// instantiated NAME — `values_collide_under_projection<0, 1>` — which rides
// the diagnostic text itself and survives even with caret echo disabled,
// exactly like the function name (see "THE MESSAGE IS PASSED AS AN ARGUMENT"
// in total_map.h). The price is that the check must be UNROLLED rather than
// looped — a loop variable cannot be a template argument — which is what the
// index_sequence expansion inside keyed_map::check is for. Slots are enum
// order, so slot I's key is key_at(I).
namespace error
{
template <std::size_t FirstSlot, std::size_t SecondSlot> void duplicate_value(const char* why);
template <std::size_t FirstSlot, std::size_t SecondSlot>
void values_collide_under_projection(const char* why);
} // namespace error

template <class E, class V, auto Proj = identity_projection{}> class keyed_map : public total_map<E, V>
{
    // Mirrors total_map's guards so a bad E or V is reported against the type
    // actually named in the source; the base re-checks behind these, but by
    // then the diagnostic would blame the delegation target.
    static_assert(std::is_enum_v<E>, "emap::keyed_map: E must be an enum type.");
    static_assert(has_enum_count<E>,
        "emap::keyed_map: could not determine the number of enumerators of E. Add a "
        "trailing sentinel enumerator (`Count` by default), specialize "
        "emap::enum_count<E>::value, or claim E with an emap::enum_count_policy<E>.");
    static_assert(std::is_copy_constructible_v<V>,
        "emap::keyed_map: V must be copy-constructible to be placed into storage.");

    // The same bar all_unique sets, stated against this type: Proj must accept
    // a const V& and its results must be equality-comparable.
    static_assert(detail::projects_comparably<decltype(Proj), V>,
        "emap::keyed_map: Proj must be invocable on const V& (a callable or a pointer "
        "to data member), and its result equality-comparable — `proj(v) == proj(v)` "
        "must convert to bool. For string ids, project to std::string_view.");

    using base = total_map<E, V>;

    // --- the id check: pairwise over the PROVEN table's values ---
    // UNROLLED over index_sequence rather than looped, so that a colliding
    // pair's slots are compile-time CONSTANTS and can ride the error
    // function's template arguments into the diagnostic (see the emap::error
    // block above for the measurement forcing this shape). N(N-1)/2
    // comparisons and N small instantiations — nothing at enumerator counts.

    // One comparison. The projection is re-materialized per call: detail::
    // project needs an lvalue, and a class-type NTTP denotes a const object.
    static consteval bool ids_equal(const base& tm, std::size_t a, std::size_t b)
    {
        auto proj = Proj;
        return static_cast<bool>(detail::project(proj, tm[base::key_at(a)]) ==
                                 detail::project(proj, tm[base::key_at(b)]));
    }

    // One collision, reported with both slots in the instantiated NAME. The
    // identity default selects the `duplicate value` diagnostic: equal values
    // mean the ROWS are wrong. A real projection selects the other: the rows
    // are usually legitimately distinct, and it is the CHOICE of Proj that
    // failed to tell them apart — question the projection before the rows.
    template <std::size_t FirstSlot, std::size_t SecondSlot> static consteval void report()
    {
        if constexpr (std::same_as<std::remove_cv_t<decltype(Proj)>, identity_projection>) {
            error::duplicate_value<FirstSlot, SecondSlot>("emap::keyed_map: duplicate value. Two rows carry equal values, so "
                "the values cannot serve as their own ids. The template arguments "
                "name the colliding slots, in enum order: key_at(slot) is the row.");
        } else {
            error::values_collide_under_projection<FirstSlot, SecondSlot>("emap::keyed_map: values collide under projection. Proj maps two "
                "rows to equal ids. If both rows surprise you, the projection does "
                "not uniquely identify a value of this table — question Proj "
                "before the rows. The template arguments name the colliding "
                "slots, in enum order: key_at(slot) is the row.");
        }
    }

    // Slot J against every earlier slot; then every J. Empty comma folds
    // (J == 0, and N == 1 overall) are well-formed no-ops.
    template <std::size_t J, std::size_t... Is>
    static consteval void check_against_earlier(const base& tm, std::index_sequence<Is...>)
    {
        ((ids_equal(tm, Is, J) ? report<Is, J>() : void()), ...);
    }

    template <std::size_t... Js>
    static consteval void check_all(const base& tm, std::index_sequence<Js...>)
    {
        (check_against_earlier<Js>(tm, std::make_index_sequence<Js>{}), ...);
    }

    // Returns its argument so the promoting constructor can initialize the
    // base from the checked table in one expression — the base is
    // copy-constructed, so no default constructor of V is ever needed,
    // matching total_map's own requirements.
    static consteval base check(const base& tm)
    {
        check_all(tm, std::make_index_sequence<base::size()>{});
        return tm;
    }

  public:
    // The id derived from each value — what find() takes.
    using id_type = detail::projected_id_t<Proj, V>;

    // PROMOTE — the primary constructor: an already-proven total_map, with the
    // id check run before the base is initialized. consteval and IMPLICIT,
    // deliberately (see CONSTRUCTION above).
    consteval keyed_map(const base& tm) : base(check(tm)) {}

    // Authoring sugar. Each form builds the total_map FIRST and promotes it,
    // so key validation and its diagnostics stay in exactly one place —
    // total_map — and the id check in exactly one other: check(), above.
    template <std::size_t M>
    consteval keyed_map(const std::array<entry<E, V>, M>& in) : keyed_map(base(in))
    {
    }

    template <std::same_as<entry<E, V>>... Rows>
    consteval keyed_map(Rows... rows) : keyed_map(base(rows...))
    {
    }

    // LOOKUP BY ID — the operation the proof licenses. A pointer, because
    // this lookup is PARTIAL (nothing proves an arbitrary id is present);
    // const, because values are immutable; constexpr, not consteval, because
    // runtime lookup of a proven table is the point. The matched value's enum
    // is recoverable positionally: key_at(found - data()).
    constexpr const V* find(const id_type& id) const
    {
        auto proj = Proj; // an lvalue for detail::project to bind
        for (std::size_t i = 0; i < base::size(); ++i) {
            const V& v = (*this)[base::key_at(i)];
            if (detail::project(proj, v) == id) {
                return &v;
            }
        }
        return nullptr;
    }
};

// Deduction guides, mirroring the base's own: E and V from the rows (or the
// promoted table), Proj left to its identity default — a PROJECTED keyed_map
// names its projection explicitly, since a projection cannot be deduced from
// rows that merely contain it.
template <class E, class V> keyed_map(const total_map<E, V>&) -> keyed_map<E, V>;
template <class E, class V, std::size_t M>
keyed_map(const std::array<entry<E, V>, M>&) -> keyed_map<E, V>;
template <class E, class V, class... Rest> keyed_map(entry<E, V>, Rest...) -> keyed_map<E, V>;

// ---------------------------------------------------------------------------
// Acceptability predicate — a compile-time answer to "would keyed_map<.., Proj>
// accept this table?", mirroring emap::buildable: the same two passing forms
// (by value, restricted to NTTP-valid tables; by pointer, general), the same
// substitution-failure mechanism, and the same portability rule — the
// CONSTRUCTION is the outermost call in the bool_constant operand, and only
// the ARGUMENT goes through a helper (total_map.h documents the measured
// compiler divergence behind that rule).
//
// keyable SUBSUMES buildable: the construction it forces runs total_map's key
// checks before the id check, so a table that would not even build is
// keyable == false — one predicate answers for the whole construction.
// keyable<Arr> (Proj defaulted) therefore reads: buildable, AND duplicate-free.
// ---------------------------------------------------------------------------
namespace detail
{
// E and V, read off the (possibly pointed-to) row array so the concept can
// name keyed_map<E, V, Proj> explicitly — CTAD cannot supply a non-defaulted
// Proj, and the construction must stay outermost, so no deducing helper may
// wrap it.
template <class A> struct entry_array_traits;
template <class E, class V, std::size_t M> struct entry_array_traits<std::array<entry<E, V>, M>> {
    using enum_type = E;
    using value_type = V;
};
template <auto X>
using entry_array_traits_for =
    entry_array_traits<std::remove_cvref_t<decltype(detail::deref_if_ptr(X))>>;
} // namespace detail

template <auto X, auto Proj = identity_projection{}>
concept keyable = requires {
    typename std::bool_constant<(
        keyed_map<typename detail::entry_array_traits_for<X>::enum_type,
                  typename detail::entry_array_traits_for<X>::value_type, Proj>(
            detail::deref_if_ptr(X)),
        true)>;
};

} // namespace emap

// ============================================================================
// SELF-TESTS
// Same contract as total_map.h's: opt-in via TOTAL_MAP_SELFTEST, compile-time
// only, a clean compile is the pass. Self-contained — it deliberately does
// NOT reuse the other headers' selftest types, so it holds even in a TU where
// those were included earlier without the macro. See tests/selftest_keyed.cpp
// for the three-line driver.
// ============================================================================
#ifdef TOTAL_MAP_SELFTEST
#include <string_view>
namespace emap::selftest
{

enum class Gem { Ruby, Jade, Opal, Count };

struct Spec {
    int wireCode;
    const char* label;
}; // pure payload — NO key member, and no operator==

// --- identity default: the values are their own ids ---
constexpr emap::keyed_map kCodes{
    entry{Gem::Ruby, 11}, entry{Gem::Jade, 22}, entry{Gem::Opal, 33}};
static_assert(std::is_same_v<decltype(kCodes), const emap::keyed_map<Gem, int>>);
static_assert(std::is_same_v<decltype(kCodes)::id_type, int>);

// the base's contract is inherited intact: total lookup, size, key recovery
static_assert(kCodes[Gem::Jade] == 22);
static_assert(kCodes.size() == 3);
static_assert(kCodes.key_at(2) == Gem::Opal);

// find(): hit and miss, at compile time (and the same body serves run time)
static_assert(kCodes.find(22) != nullptr && *kCodes.find(22) == 22);
static_assert(kCodes.find(7) == nullptr);

// the matched value's enum, recovered positionally through the inherited API
static_assert(kCodes.key_at(static_cast<std::size_t>(kCodes.find(33) - kCodes.data())) ==
              Gem::Opal);

// --- IS-A total_map: the proof only ever ADDS ---
static_assert(std::is_base_of_v<emap::total_map<Gem, int>, decltype(kCodes)>);
static_assert(std::convertible_to<const emap::keyed_map<Gem, int>&,
                                  const emap::total_map<Gem, int>&>);
// the all_unique predicate accepts it (through the base) and agrees with the
// proof the type already carries
static_assert(emap::all_unique(kCodes));
// equality reaches through the base, in both directions
constexpr emap::total_map kCodesPlain{
    entry{Gem::Opal, 33}, entry{Gem::Ruby, 11}, entry{Gem::Jade, 22}};
static_assert(kCodes == kCodesPlain);
static_assert(kCodesPlain == kCodes);

// --- promote: an already-proven table, CTAD from the primary constructor ---
constexpr emap::keyed_map kPromoted = kCodesPlain;
static_assert(std::is_same_v<decltype(kPromoted), const emap::keyed_map<Gem, int>>);
// asserted through the dereference: a miss would be a null deref, which is
// never a constant expression, so the assert still fails loudly — and gcc's
// -Waddress has nothing to say about a folded non-null pointer comparison
static_assert(*kPromoted.find(11) == 11);

// authoring through from(): the promote path composes, no from() of its own
constexpr emap::keyed_map<Gem, int> kFromFn{
    emap::total_map<Gem, int>::from([](Gem g) { return (static_cast<int>(g) + 1) * 11; })};
static_assert(kFromFn == kCodes);

// --- a projected id: a pointer to data member ---
// The labels are NOT distinct — irrelevant, and the point: only the
// PROJECTION of a value must be collision-free, not the value entire.
constexpr emap::keyed_map<Gem, Spec, &Spec::wireCode> kSpecs{
    entry{Gem::Ruby, Spec{7, "red"}},
    entry{Gem::Jade, Spec{9, "green"}},
    entry{Gem::Opal, Spec{12, "green"}},
};
static_assert(std::is_same_v<decltype(kSpecs)::id_type, int>);
static_assert(kSpecs.find(9)->label[1] == 'r');
static_assert(kSpecs.find(8) == nullptr);
static_assert(kSpecs[Gem::Opal].wireCode == 12);

// --- a projected id: a captureless lambda, written in the argument list ---
// Projecting to string_view, so id equality means CONTENT — the portable form
// for string ids, per the header notes here and on all_unique.
constexpr emap::keyed_map<Gem, Spec, [](const Spec& s) { return std::string_view{s.label}; }>
    kByLabel{
        entry{Gem::Ruby, Spec{7, "red"}},
        entry{Gem::Jade, Spec{9, "green"}},
        entry{Gem::Opal, Spec{12, "blue"}},
    };
static_assert(std::is_same_v<decltype(kByLabel)::id_type, std::string_view>);
static_assert(kByLabel.find(std::string_view{"green"})->wireCode == 9);
static_assert(kByLabel.find(std::string_view{"gray"}) == nullptr);

// --- immutable, like the base: proofs must outlive their statement ---
static_assert(!std::is_copy_assignable_v<emap::keyed_map<Gem, int>>);
static_assert(!std::is_move_assignable_v<emap::keyed_map<Gem, int>>);

// --- transform() drops the proof WITH the type — a total_map comes back ---
constexpr auto kDoubled = kCodes.transform([](int v) { return v * 2; });
static_assert(std::is_same_v<decltype(kDoubled), const emap::total_map<Gem, int>>);

// --- keyable: acceptance as a predicate, both passing forms ---
constexpr auto kRowsOk = std::array{
    entry{Gem::Ruby, 11}, entry{Gem::Jade, 22}, entry{Gem::Opal, 33}};
constexpr auto kRowsCollide = std::array{
    entry{Gem::Ruby, 11}, entry{Gem::Jade, 11}, entry{Gem::Opal, 33}};
constexpr auto kRowsPartial = std::array{entry{Gem::Ruby, 11}};
static_assert(emap::keyable<kRowsOk>);
static_assert(!emap::keyable<kRowsCollide>); // ids collide...
static_assert(emap::buildable<kRowsCollide>); // ...on a table that BUILDS fine:
                                              // keyable is strictly stronger
static_assert(!emap::keyable<kRowsPartial>); // and it subsumes buildable —
static_assert(!emap::buildable<kRowsPartial>); // a non-table is keyable false too

// by pointer, for a V that is not NTTP-valid by value (Spec holds a
// string-literal const char* — same restriction, same escape as buildable's)
inline constexpr auto kSpecRows = std::array{
    entry{Gem::Ruby, Spec{7, "red"}},
    entry{Gem::Jade, Spec{9, "green"}},
    entry{Gem::Opal, Spec{12, "green"}},
};
inline constexpr auto kSpecRowsCollide = std::array{
    entry{Gem::Ruby, Spec{7, "red"}},
    entry{Gem::Jade, Spec{7, "green"}},
    entry{Gem::Opal, Spec{12, "blue"}},
};
static_assert(emap::keyable<&kSpecRows, &Spec::wireCode>);
static_assert(!emap::keyable<&kSpecRowsCollide, &Spec::wireCode>);
// the projection decides: the SAME colliding rows are keyable under a
// projection that does tell them apart
static_assert(emap::keyable<&kSpecRowsCollide,
                            [](const Spec& s) { return std::string_view{s.label}; }>);

} // namespace emap::selftest
#endif // TOTAL_MAP_SELFTEST

#endif // KEYED_MAP_INCLUDED
