// ============================================================================
// Boost Software License - Version 1.0 - August 17th, 2003

// Copyright (c) 2026 Teo Boutin

// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:

// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// ============================================================================
// mutable_total_map.h  —  emap::mutable_total_map<E, V>
// The runtime-tunable sibling of emap::total_map. Requires C++20.
// ----------------------------------------------------------------------------
//
// WHAT IT IS
//   emap::mutable_total_map<E, V> is total_map's mutable sibling: the same
//   fixed key set and storage shape (std::array<V, N> indexed by the enum's
//   underlying value, keys validated then dropped), but VALUES MAY BE MUTATED
//   after construction and instances may be assigned.
//
//   EVERY mutable_total_map BEGINS LIFE AS A PROVEN TABLE. This header
//   contains no validation logic at all: the primary constructor THAWS an
//   already-validated total_map, and every authoring form (rows, an array of
//   rows, from(fn)) is sugar that builds the total_map first and thaws it.
//   Diagnostics for a bad table are therefore total_map's own, verbatim.
//
// INTENDED USE
//   Tables whose SHAPE is fixed at compile time but whose VALUES are tuned at
//   run time: calibration data, user-adjusted styling, live thresholds.
//   Author the baseline as a total_map — keeping the compile-time coverage
//   proof — then thaw:
//
//       constexpr emap::total_map baseline{
//           emap::entry{Color::Red,   Style{1, "red"}},
//           emap::entry{Color::Green, Style{2, "green"}},
//           emap::entry{Color::Blue,  Style{3, "blue"}},
//       };
//
//       emap::mutable_total_map live = baseline;   // thaw — at run time
//       live[Color::Red].thickness = 4;            // tune
//       if (live != baseline) { ... }              // drift is observable
//
//   The thaw is constexpr, not consteval: thawing at run time is the point.
//   The KEY invariants survive mutation untouched — keys are positional and
//   never stored, so no value edit can un-cover or duplicate a key. What
//   does NOT survive is any proof about the VALUES:
//
// WHY all_unique REFUSES THIS TYPE
//   emap::all_unique accepts only total_map, deliberately. A proof must hold
//   as long as anything relies on it, and a mutable table can drift the
//   moment after the proof is stated. State value proofs about the FROZEN
//   BASELINE, where immutability makes them hold for every instance's whole
//   lifetime; a thawed copy is precisely the object such a proof no longer
//   covers.
//
// WHAT IT DELIBERATELY DOES NOT HAVE
//   * transform() — an authoring tool; author on total_map, then thaw
//     (`emap::mutable_total_map live = baseline.transform(fn);` works
//     through the implicit thaw).
//   * Any conversion BACK to total_map — that would hand total_map a runtime
//     construction path through the back door.
//   * all_unique eligibility (above).
//
// REQUIREMENTS & GUARANTEES
//   Exactly total_map's: the same enum contiguity and enum_count discovery,
//   the same V requirements, the same rejection of bad row sets (delegated).
//   Lookup is a plain array index; the debug-only range assert guards forged
//   keys, on both the const and the mutable path.
// ============================================================================

#ifndef MUTABLE_TOTAL_MAP_INCLUDED
#define MUTABLE_TOTAL_MAP_INCLUDED

// The quote form, deliberately: it resolves relative to THIS file first, so
// the pair of headers can be copied into a project as one emap/ directory
// and work with no include-path setup — the same no-build-system install
// path total_map.h supports alone. Version macros live in total_map.h; one
// library, one version.
#include "total_map.h"

#include <array>
#include <cassert>
#include <concepts>
#include <cstddef>
#include <type_traits>
#include <utility>

namespace emap
{

template <class E, class V> class mutable_total_map
{
    // Mirrors total_map's guards so a bad E or V is reported against the
    // type actually named in the source. total_map re-checks behind these,
    // but by then the diagnostic would blame the delegation target.
    static_assert(std::is_enum_v<E>, "emap::mutable_total_map: E must be an enum type.");
    static_assert(has_enum_count<E>,
        "emap::mutable_total_map: could not determine the number of enumerators of E. Add a "
        "trailing sentinel enumerator (`Count` by default), specialize "
        "emap::enum_count<E>::value, or claim E with an emap::enum_count_policy<E>.");
    static_assert(std::is_copy_constructible_v<V>,
        "emap::mutable_total_map: V must be copy-constructible to be placed into storage.");

    static constexpr std::size_t N = enum_count_v<E>;

    static_assert(N > 0,
        "emap::mutable_total_map: E was read as having zero enumerators. If the sentinel "
        "being read is a real enumerator of your enum rather than a trailing sentinel, "
        "specialize emap::enum_count<E> with the true count.");

    std::array<V, N> data_;

    // Fill from a proven table, slot for slot: total_map stores values in
    // enum order and slot i's key is static_cast<E>(i), so slot i copies
    // tm[E(i)] through the public const interface — no friendship needed.
    template <std::size_t... Is>
    constexpr mutable_total_map(const total_map<E, V>& tm, std::index_sequence<Is...>)
        : data_{tm[static_cast<E>(Is)]...}
    {
    }

  public:
    // THAW — the primary constructor. constexpr and IMPLICIT, deliberately:
    // thawing a proven table at run time is this type's reason to exist, and
    // `emap::mutable_total_map live = baseline;` is the intended spelling.
    // There is nothing to validate — the key invariants are positional and
    // typed, and the source has already proven them.
    constexpr mutable_total_map(const total_map<E, V>& tm)
        : mutable_total_map(tm, std::make_index_sequence<N>{})
    {
    }

    // Authoring sugar. Each form builds the total_map FIRST and thaws it, so
    // validation and its diagnostics stay in exactly one place — total_map.
    // consteval like all row authoring: there is still no runtime path from
    // UNVALIDATED rows to a table, only from a proven table to a live one.
    template <std::size_t M>
    consteval mutable_total_map(const std::array<entry<E, V>, M>& in)
        : mutable_total_map(total_map<E, V>(in))
    {
    }

    template <std::same_as<entry<E, V>>... Rows>
    consteval mutable_total_map(Rows... rows)
        : mutable_total_map(total_map<E, V>(rows...))
    {
    }

    // Derive the initial state from a function of the key — total_map::from,
    // thawed. Same constraints, same by-construction totality (see its
    // block in total_map.h).
    template <class F>
        requires std::invocable<F&, E> &&
                 std::same_as<std::remove_cvref_t<std::invoke_result_t<F&, E>>, V>
    static consteval mutable_total_map from(F fn)
    {
        return mutable_total_map(total_map<E, V>::from(fn));
    }

    // Lookup, readable and WRITABLE — the point of this type. The key's TYPE
    // is checked by the signature; its VALUE only in debug, exactly as
    // total_map documents (see its CAVEATS).
    constexpr V& operator[](E e)
    {
        assert(static_cast<std::size_t>(e) < N &&
               "emap::mutable_total_map: key out of range (a sentinel used as a live value?)");
        return data_[static_cast<std::size_t>(e)];
    }
    constexpr const V& operator[](E e) const
    {
        assert(static_cast<std::size_t>(e) < N &&
               "emap::mutable_total_map: key out of range (a sentinel used as a live value?)");
        return data_[static_cast<std::size_t>(e)];
    }

    // Iteration is over VALUES, in enum order; both flavors, since mutating
    // a value cannot break any KEY invariant (there is no stored key).
    constexpr auto begin() { return data_.begin(); }
    constexpr auto end() { return data_.end(); }
    constexpr auto begin() const { return data_.begin(); }
    constexpr auto end() const { return data_.end(); }
    constexpr auto cbegin() const { return data_.cbegin(); }
    constexpr auto cend() const { return data_.cend(); }

    constexpr V* data() { return data_.data(); }
    constexpr const V* data() const { return data_.data(); }

    static constexpr std::size_t size() { return N; }

    // Key recovery and key iteration — identical to total_map's, and static
    // for the same reason: the keys are a property of the TYPE.
    static constexpr E key_at(std::size_t i)
    {
        assert(i < N && "emap::mutable_total_map: index out of range");
        return static_cast<E>(i);
    }
    static constexpr auto keys() { return detail::key_view<E>{N}; }

    // Iterate keys alongside values; the non-const view mutates through
    // .value. Non-owning, like every view.
    constexpr auto entries() { return detail::entry_view<E, V>{data_.data(), N}; }
    constexpr auto entries() const { return detail::entry_view<E, const V>{data_.data(), N}; }

    // Equality over values, slot for slot, conditionally present — the same
    // shape, for the same reasons, as total_map's (see its operator==
    // block). != is derived from == by the language.
    friend constexpr bool operator==(const mutable_total_map& a, const mutable_total_map& b)
        requires std::equality_comparable<V>
    {
        return a.data_ == b.data_;
    }

    // Heterogeneous, against the type's natural baseline: "has this live
    // table drifted from the table it thawed?" Direct rather than through
    // the implicit thaw conversion, so asking costs no copy. ONE friend
    // serves both argument orders — C++20 synthesizes the reversed
    // candidate, and being the more specialized match it beats routing
    // total_map through the converting constructor.
    friend constexpr bool operator==(const mutable_total_map& a, const total_map<E, V>& b)
        requires std::equality_comparable<V>
    {
        for (std::size_t i = 0; i < N; ++i) {
            if (!(a.data_[i] == b[static_cast<E>(i)])) {
                return false;
            }
        }
        return true;
    }
};

// Thaw with CTAD: `emap::mutable_total_map live = baseline;`.
template <class E, class V>
mutable_total_map(const total_map<E, V>&) -> mutable_total_map<E, V>;

// The authoring-sugar guides, mirroring total_map's own.
template <class E, class V, std::size_t M>
mutable_total_map(const std::array<entry<E, V>, M>&) -> mutable_total_map<E, V>;
template <class E, class V, class... Rest>
mutable_total_map(entry<E, V>, Rest...) -> mutable_total_map<E, V>;

} // namespace emap

// ============================================================================
// SELF-TESTS
// Same contract as total_map.h's: opt-in via TOTAL_MAP_SELFTEST, compile-time
// only, a clean compile is the pass. Self-contained — it deliberately does
// NOT reuse total_map.h's selftest types, so it holds even in a TU where
// total_map.h was included earlier without the macro. See
// tests/selftest_mutable.cpp for the three-line driver.
// ============================================================================
#ifdef TOTAL_MAP_SELFTEST
namespace emap::selftest
{

enum class Chan { Left, Right, Sub, Count };

constexpr emap::total_map kChanBase{
    entry{Chan::Left, 10}, entry{Chan::Right, 20}, entry{Chan::Sub, 30}};

// --- thaw: CTAD from a proven table, values slot for slot ---
constexpr emap::mutable_total_map kThawed = kChanBase;
static_assert(std::is_same_v<decltype(kThawed), const emap::mutable_total_map<Chan, int>>);
static_assert(kThawed[Chan::Left] == 10);
static_assert(kThawed[Chan::Sub] == 30);
static_assert(kThawed.size() == 3);

// mutation through operator[], in a constant expression
constexpr int thawAndMutate()
{
    emap::mutable_total_map m = kChanBase;
    m[Chan::Right] = 99;
    return m[Chan::Right];
}
static_assert(thawAndMutate() == 99);

// mutation through entries()
constexpr int mutateViaEntries()
{
    emap::mutable_total_map m = kChanBase;
    for (auto [key, value] : m.entries()) {
        value *= 2;
    }
    return m[Chan::Sub];
}
static_assert(mutateViaEntries() == 60);

// assignment is allowed — this is the mutable sibling, and reassignment is
// mutation of the coarsest grain
static_assert(std::is_copy_assignable_v<emap::mutable_total_map<Chan, int>>);
static_assert(std::is_move_assignable_v<emap::mutable_total_map<Chan, int>>);
// (kOnes is authored at namespace scope, not via from() inside the function:
// a consteval immediate invocation inside a plain constexpr function is a
// portability corner this header refuses to sit on.)
constexpr emap::mutable_total_map kOnes{
    entry{Chan::Left, 1}, entry{Chan::Right, 1}, entry{Chan::Sub, 1}};
constexpr int reassigned()
{
    emap::mutable_total_map m = kChanBase;
    m = kOnes;
    return m[Chan::Left];
}
static_assert(reassigned() == 1);

// the non-const view is the mutable one; the const path stays const
static_assert(std::is_same_v<
    decltype(std::declval<emap::mutable_total_map<Chan, int>&>().entries()),
    emap::detail::entry_view<Chan, int>>);
static_assert(std::is_same_v<
    decltype(std::declval<const emap::mutable_total_map<Chan, int>&>().entries()),
    emap::detail::entry_view<Chan, const int>>);

// --- authoring sugar: all three delegating paths agree with the thaw ---
constexpr emap::mutable_total_map kRows{
    entry{Chan::Left, 10}, entry{Chan::Right, 20}, entry{Chan::Sub, 30}};
static_assert(std::is_same_v<decltype(kRows), const emap::mutable_total_map<Chan, int>>);
constexpr emap::mutable_total_map kArr{std::array{
    entry{Chan::Sub, 30}, entry{Chan::Left, 10}, entry{Chan::Right, 20}}};
constexpr auto kFromFn = emap::mutable_total_map<Chan, int>::from(
    [](Chan c) { return (static_cast<int>(c) + 1) * 10; });
static_assert(kRows == kThawed);
static_assert(kArr == kThawed);
static_assert(kFromFn == kThawed);

// --- heterogeneous ==: drift against the baseline, both argument orders ---
static_assert(kThawed == kChanBase);
static_assert(kChanBase == kThawed);
constexpr bool driftDetected()
{
    emap::mutable_total_map m = kChanBase;
    m[Chan::Left] = 11;
    return m != kChanBase && kChanBase != m;
}
static_assert(driftDetected());

// == is conditionally present, like total_map's: a V with no operator==
// leaves the map non-comparable, cleanly
struct Mute {
    int g;
    constexpr explicit Mute(int v) : g(v) {}
};
static_assert(!std::equality_comparable<emap::mutable_total_map<Chan, Mute>>);

// key recovery and key iteration, static like total_map's
static_assert(emap::mutable_total_map<Chan, int>::key_at(1) == Chan::Right);
static_assert(emap::mutable_total_map<Chan, int>::keys().size() == 3);

// --- all_unique refuses the mutable type, BY TYPE ---
// A proof must outlive its statement; a mutable table can drift. The
// overloads take total_map only, so the proof cannot even be stated here.
template <class M>
concept all_unique_accepts_map = requires(const M& m) { emap::all_unique(m); };
static_assert(all_unique_accepts_map<emap::total_map<Chan, int>>);
static_assert(!all_unique_accepts_map<emap::mutable_total_map<Chan, int>>);

} // namespace emap::selftest
#endif // TOTAL_MAP_SELFTEST

#endif // MUTABLE_TOTAL_MAP_INCLUDED
