// ============================================================================
// Boost Software License - Version 1.0 - August 17th, 2003

// Copyright (c) 2026 Teo Boutin

// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:

// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// ============================================================================
// snapshot_map.h  —  emap::snapshot_map<K, V, N> + emap::join
// A fully immutable value-owning snapshot with proven-distinct keys of
// arbitrary literal type, producible ONLY by joining proven parts.
// Requires C++20.
// ----------------------------------------------------------------------------
//
// WHAT IT IS
//   The library's first non-enum-indexed table. Parallel arrays — keys and
//   values, slot for slot — where slot i IS the association: like
//   total_map's "no stored keys", nothing can disagree with its own slot.
//   The keys are proven pairwise distinct, but NOT by any check in this
//   header: snapshot_map has no public validating constructor at all. Its
//   SOLE producer is emap::join (below), so every snapshot descends from
//   already-proven parts, and this type merely carries the combined proof.
//
// INTENDED USE
//   The end of a proof chain: an id-indexed view of per-enum config,
//   assembled at compile time from tables that each proved their own part.
//
//       enum class Jack { J0, J1, J2, Count };   // wire-facing enum
//       enum class Amp  { Lo, Mid, Hi, Count };  // internal enum
//       struct Patch { int wire; };              // carries the public id
//       struct Conf  { int gain; };              // per-Amp config
//
//       constexpr emap::keyed_map<Jack, Patch, &Patch::wire> patches{...};
//       constexpr emap::bijection link{...};     // Jack <-> Amp
//       constexpr emap::total_map confs{...};    // Amp -> Conf
//
//       constexpr auto byWire = emap::join(patches, link, confs);
//       static_assert(byWire.find(100)->gain == 5);  // wire id -> Conf
//
// WHAT THE PROOF LICENSES — find(), and only find()
//   find(id) returns a pointer to THE value stored under that key, or
//   nullptr: id -> value is a PARTIAL lookup (nothing proves an arbitrary
//   id is present, only that a present id is unambiguous), and the
//   signature says so — same contract as keyed_map::find. constexpr, not
//   consteval: runtime lookup of a compile-time-proven table is the point.
//   O(N) scan; a sorted index would be an invisible optimization and can
//   arrive later without changing this API. There is deliberately NO
//   operator[] (no totality claim exists over an open key type K), no
//   iteration, no mutable path — every absent operation is an absent claim.
//
// CONSTRUCTION — none, publicly
//   join is the one producer, entering through a private tagged constructor
//   (the same reasoning as bijection's inverse() door: the parts already
//   carry the proof, and a check that cannot fail would only state that the
//   proof is doubted). Copy/move CONSTRUCTION stay — join returns by value,
//   and deriving a copy of a proven snapshot is fine; assignment is deleted,
//   like every immutable type here, so an instance can never detach from
//   the table it was proven as.
//
// THE OUTLIVING CLAIM, SCOPED — read before storing string_view ids
//   V values are COPIED out of the joined tables: on the VALUE side a
//   snapshot is self-contained and may outlive its inputs. The KEYS are
//   projected ids, and an id type like std::string_view ALIASES storage it
//   does not own: ids pointing into string literals or a namespace-scope
//   constexpr table are fine (static storage outlives everything), and
//   constant evaluation keeps a genuine dangle LOUD — a pointer into a
//   vanished temporary is not a constant expression — but the self-
//   containment claim is the VALUES', not the keys'. (The same scoping
//   applies transitively to a V that itself holds pointers, as everywhere
//   in this library.)
//
// DIAGNOSTICS
//   None of its own — deliberately. join CANNOT fail (see its block), and
//   every way to reach a snapshot runs the producing types' own checks with
//   their own diagnostics. A collision surfaces UPSTREAM, at keyed_map
//   construction, where the colliding slots are named;
//   tests/negative/snapshot_upstream_collision.cpp pins that.
//
// REQUIREMENTS & GUARANTEES
//   * K and V must be literal types, copy-constructible; K equality-
//     comparable. All guaranteed upstream by join's inputs, and asserted
//     here against THIS type's name so a future construction path cannot
//     regress the diagnostic.
//   * Keys pairwise distinct (from the keyed_map input's proof) — which is
//     what makes find()'s answer well-defined.
//   * The snapshot is exactly the third table RE-KEYED by the first one's
//     ids: every row represented exactly once (from the bijection input's
//     proof; see join below).
// ============================================================================

#ifndef SNAPSHOT_MAP_INCLUDED
#define SNAPSHOT_MAP_INCLUDED

// Quote form, deliberately (copy-pastable emap/ directory; see total_map.h).
// Both refinement headers, because join's signature names both refinements;
// they each pull in total_map.h. Version macros live in total_map.h.
#include "bijection.h"
#include "keyed_map.h"

#include <array>
#include <concepts>
#include <cstddef>
#include <type_traits>
#include <utility>

namespace emap
{

template <class K, class V, std::size_t N> class snapshot_map;

// Declared before the class so the friend declaration inside it refers to
// THIS template rather than silently declaring a new, invisible one.
// Definition and full documentation below the class.
template <class E1, class V1, auto P1, class E2, class V2>
consteval snapshot_map<detail::projected_id_t<P1, V1>, V2, enum_count_v<E1>>
join(const keyed_map<E1, V1, P1>& a, const bijection<E1, E2>& b,
     const total_map<E2, V2>& m2);

template <class K, class V, std::size_t N> class snapshot_map
{
    // Guaranteed upstream by join's inputs (keyed_map's projects_comparably
    // bar, total_map's V requirements), but asserted against THIS type's
    // name so a future direct construction path cannot regress the
    // diagnostic.
    static_assert(std::is_copy_constructible_v<K>,
        "emap::snapshot_map: K must be copy-constructible to be placed into storage.");
    static_assert(std::is_copy_constructible_v<V>,
        "emap::snapshot_map: V must be copy-constructible to be placed into storage.");
    static_assert(requires(const K& a, const K& b) {
        { a == b } -> std::convertible_to<bool>;
    }, "emap::snapshot_map: K must be equality-comparable — find(id) compares ids.");

    // Parallel arrays: slot i IS the association. Keys ARE stored here —
    // unlike total_map's enum keys they are not recoverable from position —
    // but they are as frozen as the values, so they still cannot disagree
    // with their slots.
    std::array<K, N> keys_;
    std::array<V, N> values_;

    // --- the tagged door: join is the sole producer ---
    // Same reasoning as bijection's inverse() door, recorded there in full:
    // the inputs already carry the proof, so a re-check here could not fail
    // and would only state that the proof is doubted. Private tag + the
    // friendship below keep the public invariant: no reachable constructor
    // skips a proof, because no reachable validating constructor exists.
    struct proven_join_t {};

    template <class E1, class V1, auto P1, class E2, class V2>
    friend consteval snapshot_map<detail::projected_id_t<P1, V1>, V2, enum_count_v<E1>>
    join(const keyed_map<E1, V1, P1>&, const bijection<E1, E2>&,
         const total_map<E2, V2>&);

    // Pack-expanded per slot so neither K nor V needs a default constructor
    // (each element is copy-initialized from the callable's result) —
    // total_map's from_fn_t pattern, for two arrays.
    template <class KeyFn, class ValFn, std::size_t... Is>
    consteval snapshot_map(proven_join_t, KeyFn& keyFn, ValFn& valFn,
                           std::index_sequence<Is...>)
        : keys_{keyFn(Is)...}, values_{valFn(Is)...}
    {
    }

  public:
    // LOOKUP BY ID — the one operation. A pointer, because the lookup is
    // PARTIAL; const, because everything here is; constexpr, because runtime
    // lookup of a proven table is the point. See the top block.
    constexpr const V* find(const K& id) const
    {
        for (std::size_t i = 0; i < N; ++i) {
            if (keys_[i] == id) {
                return &values_[i];
            }
        }
        return nullptr;
    }

    static constexpr std::size_t size() { return N; }

    // Immutable: copy/move CONSTRUCTION stay (join returns by value, and a
    // copy of a proven snapshot is proven), assignment is deleted — see
    // total_map's identical block for the -Wdeprecated-copy note behind
    // declaring the constructors as defaulted.
    constexpr snapshot_map(const snapshot_map&) = default;
    constexpr snapshot_map(snapshot_map&&) = default;
    snapshot_map& operator=(const snapshot_map&) = delete;
    snapshot_map& operator=(snapshot_map&&) = delete;
};

// ---------------------------------------------------------------------------
// join — the snapshot's sole producer. For each E1 key e, the snapshot pairs
// P1(a[e]) — the id — with m2[b[e]] — the value. consteval; NO VALIDATION IN
// THE BODY, and none omitted: the signature is the entire proof.
//
// Which argument proves what — precisely:
//   * KEY DISTINCTNESS comes from `a` ALONE: the snapshot's keys are a's
//     projected ids, proven collision-free at a's construction.
//   * COVERAGE comes from the totality of all three arguments.
//   * `b` being a BIJECTION is demanded for a guarantee about the RESULT,
//     not for its validity: it makes the snapshot exactly m2 RE-KEYED by
//     a's ids — every row of m2 represented exactly once, nothing dropped,
//     nothing duplicated. (A merely-total bridge would still produce a
//     valid snapshot, but could hit one E2 row twice and silently miss
//     another.) Bijectivity is NOT what makes the keys distinct — a alone
//     does that.
//
// V2 values are COPIED (self-contained on the value side; the keys' scoping
// is the aliasing block at the top). Accepting these parameter types also
// accepts anything publicly derived from them — fine: the proof rides the
// base subobject. emap::mutable_total_map matches NONE of the three
// positions, by signature — the selftests pin that refusal.
//
// join cannot fail, so there is no negative test OF join — only the
// upstream one showing where a collision actually surfaces.
// ---------------------------------------------------------------------------
template <class E1, class V1, auto P1, class E2, class V2>
consteval snapshot_map<detail::projected_id_t<P1, V1>, V2, enum_count_v<E1>>
join(const keyed_map<E1, V1, P1>& a, const bijection<E1, E2>& b,
     const total_map<E2, V2>& m2)
{
    using result_type = snapshot_map<detail::projected_id_t<P1, V1>, V2, enum_count_v<E1>>;
    auto keyFn = [&a](std::size_t i) {
        auto proj = P1; // an lvalue for detail::project to bind
        return detail::project(proj, a[a.key_at(i)]);
    };
    auto valFn = [&b, &m2](std::size_t i) -> V2 { return m2[b[b.key_at(i)]]; };
    return result_type(typename result_type::proven_join_t{}, keyFn, valFn,
                       std::make_index_sequence<enum_count_v<E1>>{});
}

} // namespace emap

// ============================================================================
// SELF-TESTS
// Same contract as total_map.h's: opt-in via TOTAL_MAP_SELFTEST, compile-time
// only, a clean compile is the pass. This TU transitively compiles EVERY
// header's selftests, which is why all names here are fresh. See
// tests/selftest_snapshot.cpp for the three-line driver.
// ============================================================================
#ifdef TOTAL_MAP_SELFTEST
#include <string_view>
// The refusal checks below need the mutable sibling IN THE TEST TU; the
// header proper never touches it — refinements build on the immutable
// total_map only.
#include "mutable_total_map.h"
namespace emap::selftest
{

// --- the worked example: wire enum <-> internal enum -> config ---
enum class Jack { J0, J1, J2, Count };
enum class Amp { Lo, Mid, Hi, Count };

struct Patch {
    int wire;
};
struct Conf {
    int gain;
};

constexpr emap::keyed_map<Jack, Patch, &Patch::wire> kPatches{
    entry{Jack::J0, Patch{100}}, entry{Jack::J1, Patch{200}}, entry{Jack::J2, Patch{300}}};
constexpr emap::bijection kLink{
    entry{Jack::J0, Amp::Mid}, entry{Jack::J1, Amp::Lo}, entry{Jack::J2, Amp::Hi}};
constexpr emap::total_map kConfs{
    entry{Amp::Lo, Conf{1}}, entry{Amp::Mid, Conf{5}}, entry{Amp::Hi, Conf{9}}};

constexpr auto kSnap = emap::join(kPatches, kLink, kConfs);

// join's result type is exact — id type off the projection, size off E1
static_assert(std::is_same_v<decltype(kSnap), const emap::snapshot_map<int, Conf, 3>>);
static_assert(kSnap.size() == 3);

// id -> V2 hits follow the composition Jack -> Amp -> Conf; misses are honest
static_assert(kSnap.find(100)->gain == 5); // J0 -> Mid
static_assert(kSnap.find(200)->gain == 1); // J1 -> Lo
static_assert(kSnap.find(300)->gain == 9); // J2 -> Hi
static_assert(kSnap.find(42) == nullptr);

// --- string_view ids: the supported aliasing case (static storage) ---
struct Badge {
    const char* name;
};
constexpr emap::keyed_map<Jack, Badge,
    [](const Badge& b) { return std::string_view{b.name}; }>
    kBadges{entry{Jack::J0, Badge{"alpha"}}, entry{Jack::J1, Badge{"beta"}},
            entry{Jack::J2, Badge{"gamma"}}};
constexpr auto kByName = emap::join(kBadges, kLink, kConfs);
static_assert(std::is_same_v<decltype(kByName),
                             const emap::snapshot_map<std::string_view, Conf, 3>>);
static_assert(kByName.find(std::string_view{"beta"})->gain == 1);
static_assert(kByName.find(std::string_view{"delta"}) == nullptr);

// --- the surface is sealed: join is the sole producer ---
using Snap = emap::snapshot_map<int, Conf, 3>;
static_assert(std::is_copy_constructible_v<Snap>); // join returns by value...
static_assert(std::is_move_constructible_v<Snap>); // ...and a copy stays proven
static_assert(!std::is_default_constructible_v<Snap>);
// no public validating construction: raw parallel arrays are refused
static_assert(!std::is_constructible_v<Snap, std::array<int, 3>, std::array<Conf, 3>>);
static_assert(!std::is_copy_assignable_v<Snap>);
static_assert(!std::is_move_assignable_v<Snap>);

// --- mutable tables are refused BY SIGNATURE, at every position ---
// Through concepts, necessarily: a requires-expression OUTSIDE a templated
// entity hard-errors on an invalid expression instead of answering false —
// only substitution into a template gets the failure-tolerant reading.
template <class T>
concept join_accepts_as_m2 = requires(const T& t) { emap::join(kPatches, kLink, t); };
template <class T>
concept join_accepts_as_a = requires(const T& t) { emap::join(t, kLink, kConfs); };
static_assert(join_accepts_as_m2<emap::total_map<Amp, Conf>>); // the real type passes...
static_assert(join_accepts_as_a<emap::keyed_map<Jack, Patch, &Patch::wire>>);
static_assert(!join_accepts_as_m2<emap::mutable_total_map<Amp, Conf>>); // ...a live one never
static_assert(!join_accepts_as_a<emap::mutable_total_map<Jack, Patch>>);

} // namespace emap::selftest
#endif // TOTAL_MAP_SELFTEST

#endif // SNAPSHOT_MAP_INCLUDED
