// ============================================================================
// Boost Software License - Version 1.0 - August 17th, 2003

// Copyright (c) 2026 Teo Boutin

// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:

// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// ============================================================================
// total_map.h  —  emap::total_map<E, V>
// A compile-time-checked, exhaustive, O(1) map from an enum to values of V.
// Requires C++20.
// ----------------------------------------------------------------------------
//
// WHAT IT IS
//   emap::total_map<E, V> is a fixed-size total map: exactly one V per
//   enumerator of E, stored in a std::array<V, N> indexed by the enum's
//   underlying value. Lookup is a plain array index — no hashing, no branching,
//   no allocation. "Total" is meant in the mathematical sense: the map is a
//   total function from E, defined on every enumerator, and the compiler proves
//   it.
//
//   It is authored from `emap::entry<E, V>` rows, each pairing a key with a
//   value: `entry{Key, Value}`. Rows may be passed directly, or as one
//   std::array (the array form is what emap::buildable<> takes). Construction is
//   `consteval` and REFUSES TO COMPILE unless every enumerator is present
//   exactly once. The keys exist ONLY to validate and place the rows; once
//   validated they are DROPPED. Storage is a bare std::array<V, N> — the key is
//   not kept in each element, so it cannot go stale and costs no space. The key
//   for any slot is recoverable in O(1) from its position, via entries() or
//   key_at() (see below).
//
// INTENDED USE
//   Hand-authored, `constexpr` lookup tables of small/simple data, known in full
//   at compile time, where you want the compiler to guarantee exhaustiveness —
//   e.g. per-enum config: colors, labels, thresholds, dispatch parameters.
//   Author the table as one list of rows and let total_map prove you covered
//   every case. There is no factory: CTAD deduces E and V from the rows.
//
//       enum class Color { Red, Green, Blue, Count };
//       struct Style { int thickness; const char* name; }; // NO key member
//
//       constexpr emap::total_map styles{
//           emap::entry{Color::Red,   Style{1, "red"}},
//           emap::entry{Color::Green, Style{2, "green"}},
//           emap::entry{Color::Blue,  Style{3, "blue"}},  // omit one -> error
//       };
//       static_assert(styles[Color::Green].thickness == 2);
//
//   For a scalar payload no wrapper is needed — the value is stored (and read)
//   directly, with no `.value` indirection:
//
//       constexpr emap::total_map cost{
//           emap::entry{Color::Red, 1250.0}, emap::entry{Color::Green, 500.0},
//           emap::entry{Color::Blue, 625.0},
//       };
//       static_assert(cost[Color::Red] == 1250.0);
//
//   To iterate keys alongside values, use entries(). Values come back by
//   reference, so they can be mutated through the view:
//
//       for (auto [color, style] : styles.entries())
//           use(color, style);
//
//   entries() yields emap::entry_ref<E, V> — named .key/.value members, the
//   same vocabulary as the entry rows you authored with. The view is
//   non-owning: entries() on a temporary dangles, as with any view. The
//   iterator models std::forward_iterator, so if YOU include <ranges> it
//   composes with std::views; this header does not include <ranges> itself.
//
//   It is NOT a runtime container: there is no insert/erase and no runtime
//   construction path. Once built, VALUES may be mutated freely (there is no
//   stored key to desynchronize); the set of keys is fixed. If you need to
//   populate a map at runtime, this is the wrong tool.
//
// REQUIREMENTS (what it relies on to work)
//   * C++20: consteval, concepts/requires-clauses, class template argument
//     deduction, and aggregate CTAD for `entry`.
//   * The enum E must have CONTIGUOUS underlying values 0..N-1. Storage is
//     indexed by static_cast<std::size_t>(key), so a gap or a non-zero base
//     would misindex. This is the key precondition; emap::enum_count (below)
//     only supplies the COUNT N, it does not change the contiguity requirement.
//   * N (the enumerator count) is discovered via emap::enum_count<E>::value,
//     which by default reads a trailing `Count` sentinel (an extra enumerator
//     whose value equals the number of real enumerators). For a project whose
//     sentinel is spelled otherwise, one emap::enum_count_policy teaches the
//     spelling once; for an enum with no sentinel at all, specialize
//     emap::enum_count<E> (both below) — the enum must still be contiguous from
//     0. A missing count is reported with a clear static_assert.
//   * V must be a literal type and copy-constructible (so it is usable in
//     constant expressions and can be placed into storage). It need NOT be
//     default-constructible. Scalars, pointers, and aggregates of literal types
//     all qualify. V does NOT need to carry its own key.
//   * The input array must itself be a constant expression (built from constant
//     data), because construction is consteval.
//
// GUARANTEES
//   * Total: every enumerator has a value (missing one -> compile error).
//   * Unique: no enumerator is supplied twice (duplicate -> compile error).
//   * Correct size: the input array length must equal N (mismatch -> compile
//     error) — a consequence of the two above rather than a separate check: too
//     few rows leave an enumerator uncovered, and too many cannot all be
//     distinct and in range. All three are enforced by a `throw` inside the
//     consteval builder: a taken throw is not a constant expression, so it
//     aborts compilation.
//   * O(1) lookup; values are stored in enum order regardless of input order.
//   * Keys are not stored, so no element can ever disagree with its own slot.
//
// THE ONE THING IT DOES NOT PROVE — read this before trusting the word "total"
//   Everything above is proved against N. N ITSELF IS TRUSTED INPUT. C++20 has
//   no reflection, so this header can prove:
//       "your table covers 0..N-1 exactly once"
//   and cannot prove:
//       "N is the number of enumerators of E"
//   If N is wrong and TOO SMALL, a table covering 0..N-1 is accepted while the
//   enumerators from N onward are silently uncovered — the completeness promise
//   degrades quietly. That is the single hole in this design, and it exists no
//   matter how you supply N:
//     * Via the `Count` sentinel: N is wrong if `Count` is a REAL enumerator
//       rather than a trailing sentinel (e.g. `enum class Metric { Sum, Count,
//       Mean, Max }` reads N == 1). Usually loud — authoring the real
//       enumerators trips the out-of-range check, whose message names this
//       suspicion — but silent if you happen to author exactly 0..N-1.
//     * Via a hand-written emap::enum_count<E>: N is wrong once it goes STALE,
//       i.e. as soon as anyone adds an enumerator and forgets to bump it. A
//       stale count too LARGE is loud in the other direction — no row can cover
//       the surplus slot, so the coverage check fires and its message names
//       this suspicion too.
//   A sentinel is preferred precisely because it SELF-MAINTAINS: add an
//   enumerator and N follows automatically, so the stale case cannot arise. Any
//   override that READS a sentinel keeps that property — an
//   emap::enum_count_policy for a project, or an emap::enum_count specialization
//   pointed at one enum's own sentinel. Only a hand-written NUMBER can go stale,
//   which is why it is the last resort.
//   Rule of thumb: use the trailing `Count` sentinel. If your house sentinel is
//   spelled otherwise, write one emap::enum_count_policy; if a single enum
//   spells its own, point an emap::enum_count specialization at that sentinel.
//   Hand-write a number only for an enum with no sentinel to read.
//
// WHAT FAILS TO COMPILE (by design)
//   * An input array missing any enumerator.
//   * An input array containing a duplicate key.
//   * An input array whose length != N.
//   * A key whose static_cast<size_t> is >= N.
//   Direct construction of such a table is a hard compile error. Separately,
//   whether construction WOULD fail is itself a compile-time predicate,
//   emap::buildable, which takes the table two ways (see its block below for
//   full details):
//     * emap::buildable<Arr>  — by value; cleanest syntax, but needs Arr to be
//       a valid non-type template parameter (structural type AND NTTP-valid
//       values). A `const char*` from a string literal, or a non-structural V
//       like std::string_view, is a hard error here even though the table
//       builds.
//     * emap::buildable<&Arr> — by pointer; works for ANY buildable value type
//       (string_view, literal strings, ...). Requires only that Arr have static
//       storage duration so &Arr is a constant expression.
//   For non-structural V where you cannot name the table, fall back to the
//   must-not-compile driver at the very bottom of this file.
//
// CAVEATS
//   * operator[] takes E, so the KEY'S TYPE is checked at compile time (an int,
//     or another enum, will not convert). Its VALUE is not: a runtime E forged
//     outside 0..N-1 — by a cast, or by a `Count` sentinel used as a live
//     "none/all" value — indexes out of bounds. A debug-only assert catches
//     that (compiled away under NDEBUG); in release the contract is an array's.
//     Constant-expression subscripts are fully checked either way.
//   * No reflection in C++20 means "all enumerators" is inferred from N +
//     contiguity, not read from the language. Under C++26 static reflection the
//     enum_count/Count convention becomes unnecessary.
// ============================================================================

#ifndef TOTAL_MAP_INCLUDED
#define TOTAL_MAP_INCLUDED

// Version of this header. MAJOR/MINOR/PATCH are the SINGLE SOURCE OF TRUTH:
// both TOTAL_MAP_VERSION and TOTAL_MAP_VERSION_STRING are derived from them
// below, so the three spellings cannot drift apart. There is no generation step,
// which is what keeps the header copy-pastable into a project with no build
// system — a supported install path.
//
// CMakeLists.txt carries the same version in project(VERSION) and checks it
// against these three at configure time. That check is the only thing holding
// the two sides together, and it matters because they are published to
// DIFFERENT install paths: find_package() resolves against project(VERSION),
// while a bare header copy has no build system to ask and can only read these
// macros.
//
// TOTAL_MAP_VERSION is ordered and comparable, so a consumer can gate on a
// version the way they would with __cplusplus:
//
//     #if TOTAL_MAP_VERSION >= 10200  // 1.2.0 or newer
#define TOTAL_MAP_VERSION_MAJOR 0
#define TOTAL_MAP_VERSION_MINOR 1
#define TOTAL_MAP_VERSION_PATCH 0
#define TOTAL_MAP_VERSION                                                      \
    (TOTAL_MAP_VERSION_MAJOR * 10000 + TOTAL_MAP_VERSION_MINOR * 100 +         \
     TOTAL_MAP_VERSION_PATCH)

// That encoding is ordered only while MINOR and PATCH each stay below 100. At
// 100 a field carries into the one above it and two distinct versions collide —
// 0.1.100 and 0.2.0 both encode as 200 — which silently breaks every consumer's
// `#if TOTAL_MAP_VERSION >= ...` gate rather than failing loudly. This guards
// THIS library's release process, not any consumer's use: it can only fire on a
// version bump here, and it costs a compile-time integer comparison.
static_assert(TOTAL_MAP_VERSION_MINOR < 100 && TOTAL_MAP_VERSION_PATCH < 100,
    "total_map: VERSION_MINOR and VERSION_PATCH must each stay below 100, or "
    "TOTAL_MAP_VERSION stops being ordered and consumer version gates silently break.");

// Derived, not written out, so it cannot contradict the components above.
//
// The two-step stringify is necessary, not ceremony: the inner macro stringifies
// its argument AS WRITTEN, so the outer one is what forces
// TOTAL_MAP_VERSION_MAJOR to expand to its value first. Both helpers must stay
// defined — TOTAL_MAP_VERSION_STRING is expanded lazily at the point of USE, so
// #undef-ing them here would break it at every call site.
//
// The result is adjacent string literals joined by the usual translation-phase-6
// concatenation, which is a genuine literal for every ordinary use: an
// initializer, a constant expression, a std::string_view. The one difference
// from a hand-written "0.1.0" is that it is not a single preprocessing TOKEN, so
// passing it to a macro that stringifies its own argument yields the unexpanded
// spelling rather than the version.
#define TOTAL_MAP_STRINGIFY_(x) #x
#define TOTAL_MAP_STRINGIFY(x) TOTAL_MAP_STRINGIFY_(x)
#define TOTAL_MAP_VERSION_STRING                                               \
    TOTAL_MAP_STRINGIFY(TOTAL_MAP_VERSION_MAJOR) "."                           \
    TOTAL_MAP_STRINGIFY(TOTAL_MAP_VERSION_MINOR) "."                           \
    TOTAL_MAP_STRINGIFY(TOTAL_MAP_VERSION_PATCH)

#include <array>
#include <cassert>
#include <cstddef>
#include <concepts>
#include <iterator>
#include <type_traits>
#include <utility>

// ---------------------------------------------------------------------------
// Customization point: number of enumerators of E.
//
// Default: a contiguous enum 0..Count-1 with a trailing `Count` sentinel. This
// is the default because it SELF-MAINTAINS — add an enumerator and N follows —
// which a hand-written count cannot do. See "THE ONE THING IT DOES NOT PROVE"
// at the top: N is trusted either way, and a stale hand-written N fails exactly
// as silently as a misread sentinel.
//
// There are three ways to override it, on two axes: a RULE (reads the enum, so
// it self-maintains) versus a NUMBER (hand-written, so it can go stale), and a
// whole PROJECT versus one ENUM.
//
//                     | a RULE                  | a NUMBER
//      ---------------+-------------------------+------------------------
//      whole project  | 1. enum_count_policy    | —
//      one enum       | 2. enum_count, reading  | 3. enum_count, with a
//                     |    that enum's sentinel |    literal count
//
// Prefer the first that fits. Reach for 3 only when there is no sentinel to
// read: it is the one form that can go stale.
//
// 1. A POLICY — a RULE, for a whole project. If your house sentinel is spelled
//    something other than `Count`, teach it ONCE and every enum follows. No
//    per-enum annotation, no macro, no build-time configuration:
//
//        namespace emap {
//        template <class E>
//            requires (std::is_enum_v<E> && requires { E::Size; })
//        struct enum_count_policy<E>
//            : std::integral_constant<std::size_t,
//                                     static_cast<std::size_t>(E::Size)> {};
//        }
//
//    A policy READS the enum, so like the default it SELF-MAINTAINS and cannot
//    go stale. It is also ADDITIVE: a third-party library whose enums use the
//    stock `Count` sentinel keeps working right beside it. A policy outranks the
//    `Count` rule, so an enum carrying both spellings resolves to the policy
//    rather than being ambiguous.
//
//    Put the policy in a header your enum declarations include. A translation
//    unit that never sees it reads the stock `Count` rule instead — for a
//    sentinel-only enum that is loud (enum_count stays incomplete and the
//    static_assert below fires), but the discipline is worth keeping.
//
//    Specialize enum_count_policy ONLY with a constrained partial specialization
//    — a rule. An EXPLICIT enum_count_policy<E>, for one enum, also works and
//    even outranks a project policy, but form 2 below says the same thing more
//    directly; prefer it.
//
// 2. AN EXPLICIT SPECIALIZATION READING THE SENTINEL — a RULE, for one enum.
//    When a single enum's sentinel is spelled its own way, point the trait at
//    it. Same shape as specializing std::tuple_size, so the ::value member and
//    the _v alias are where you expect:
//
//        namespace app { enum class Dir { North, East, South, West, DirCount }; }
//
//        namespace emap {
//        template <> struct enum_count<app::Dir>
//            : std::integral_constant<std::size_t,
//                                     static_cast<std::size_t>(app::Dir::DirCount)> {};
//        }
//
//    The static_cast is REQUIRED, not decoration: integral_constant's second
//    argument is a std::size_t, and a scoped enum will not convert to one
//    implicitly. Writing `app::Dir::DirCount` bare is a compile error.
//
//    This reads the enum, so it SELF-MAINTAINS exactly like a policy or the
//    default: add an enumerator and N follows. Prefer it over form 3 whenever
//    the enum has any sentinel at all. It is the right choice for a one-off
//    (a lone enum whose sentinel matches nothing else in the project), and for
//    an enum whose sentinel varies per enum — `NUM_COLORS`, `kDirCount` — which
//    no single policy can name.
//
//    An explicit specialization outranks BOTH the policy tier and the `Count`
//    rule, so this is also how you override a project-wide policy for one enum.
//
// 3. AN EXPLICIT SPECIALIZATION WITH A COUNT — a NUMBER, for one enum. The last
//    resort, for an enum with NO usable sentinel to read:
//
//        namespace emap {
//        template <> struct enum_count<MyEnum>
//            : std::integral_constant<std::size_t, /* number of enumerators */> {};
//        }
//
//    Two cases need it:
//      a. No sentinel at all: `enum class Dir { North, East, South, West };`
//      b. The only trailing enumerator is A REAL VALUE IN ITS OWN RIGHT, so
//         reading it would be wrong — e.g. `enum class Metric { Sum, Count,
//         Mean, Max };` reads N == 1, and `enum class Agg { Count, Sum, Avg };`
//         reads N == 0.
//    YOU own keeping the number current when the enum grows. This is the ONLY
//    form that can go stale, which is why it is last.
//
// Any override must appear BEFORE the enum's first use with total_map. A
// trait cannot be specialized after it has been implicitly instantiated, so a
// use that comes first permanently locks in the wrong N — with a diagnostic
// about "specialization after instantiation" rather than anything about counts.
// Put the specialization directly under the enum's own declaration, and the
// policy in a header those declarations include, and this cannot arise.
//
// Only `Count` is recognised by DEFAULT — not COUNT, kCount, _Count or any other
// spelling. That is deliberate: each extra spelling widens the chance of
// colliding with a real enumerator (COUNT is *more* likely to be a real value
// than Count, in SQL and statistics code), and a collision costs a silently
// under-covered map. One recognised spelling keeps the guess narrow and
// predictable. A policy lets a project opt into a second spelling FOR ITSELF
// without widening the guess for anyone who did not ask.
//
// (The enum must still be contiguous starting at 0.)
// ---------------------------------------------------------------------------
namespace emap
{

// Consumer tier. Primary is deliberately UNDEFINED: a consumer claims enums by
// adding a constrained partial specialization (see the block above). The library
// never specializes this itself.
template <class E> struct enum_count_policy;

namespace detail
{
template <class E>
concept has_count_sentinel = requires { E::Count; };
template <class E>
concept has_count_policy = requires { enum_count_policy<E>::value; };
}

template <class E> struct enum_count;

// Tier 1: a consumer policy, when one claims E.
template <class E>
    requires detail::has_count_policy<E>
struct enum_count<E> : std::integral_constant<std::size_t, enum_count_policy<E>::value> {
};

// Tier 2: the stock `Count` sentinel — only when no policy claims E.
//
// The `!has_count_policy` term is load-bearing, not belt-and-braces. Without it,
// an enum carrying both spellings matches two partial specializations whose
// constraints are unrelated by subsumption: an ambiguous partial specialization,
// which is a HARD ERROR. It is also not interceptable — the ambiguity fires
// during instantiation, outside the immediate context, so it is an error even
// inside has_enum_count's requires-clause and no static_assert can attach a
// friendly message to it. This term makes the two constraints mutually
// exclusive, so exactly one specialization ever matches and the ambiguity cannot
// form. Partial ORDERING between the tiers is never consulted, which is why the
// non-subsumable `!` costs nothing here.
template <class E>
    requires (detail::has_count_sentinel<E> && !detail::has_count_policy<E>)
struct enum_count<E> : std::integral_constant<std::size_t, static_cast<std::size_t>(E::Count)> {
};

template <class E> inline constexpr std::size_t enum_count_v = enum_count<E>::value;

// True iff N is discoverable for E (either a `Count` sentinel or a user
// specialization of enum_count<E> provides ::value). Used for a friendly
// diagnostic instead of a raw "incomplete type" error.
template <class E>
concept has_enum_count = std::is_enum_v<E> && requires { enum_count<E>::value; };

// ---------------------------------------------------------------------------
// entry<E, V> — an authoring row: a key paired with its value. Keys live only
// in the input; total_map validates them and then drops them. Aggregate, so
// `entry{Color::Red, 42}` deduces entry<Color, int>.
// ---------------------------------------------------------------------------
template <class E, class V> struct entry {
    E key;
    V value;
};
template <class E, class V> entry(E, V) -> entry<E, V>;

// ---------------------------------------------------------------------------
// entry_ref<E, V> — what entries() yields: a key by value, a reference to the
// value living in the map. Named members (.key/.value), matching `entry`,
// rather than std::pair's .first/.second.
//
// The conversion to entry<E, V> is not decorative. It is what lets the iterator
// declare an honest value_type (a real value, not a reference-holder) while
// still satisfying indirectly_readable, which requires
// common_reference_with<iter_reference_t&&, iter_value_t&>. std::pair gets this
// from its converting constructor; a bare aggregate has no such conversion and
// fails the concept outright — it would not even model input_iterator. V is
// const-qualified on the const entries() path, hence remove_const_t here.
// ---------------------------------------------------------------------------
template <class E, class V> struct entry_ref {
    E key;
    V& value;
    constexpr operator entry<E, std::remove_const_t<V>>() const { return {key, value}; }
};

namespace detail
{
// Forward iterator over (key, value&) proxies. Storage is indexed by the enum's
// underlying value, so the key for slot i is just static_cast<E>(i) — the same
// recovery key_at() performs. V is const-qualified on the const path.
template <class E, class V> class entry_iterator
{
    V* base_ = nullptr;
    std::size_t i_ = 0;

  public:
    using value_type = entry<E, std::remove_const_t<V>>;
    using reference = entry_ref<E, V>;
    using difference_type = std::ptrdiff_t;
    using iterator_concept = std::forward_iterator_tag;
    // Legacy category stays input_iterator_tag: Cpp17ForwardIterator requires a
    // true reference and ours is a proxy. The C++20 iterator_concept above is
    // what std::ranges actually consults.
    using iterator_category = std::input_iterator_tag;

    entry_iterator() = default;
    constexpr entry_iterator(V* base, std::size_t i) : base_(base), i_(i) {}

    constexpr reference operator*() const { return {static_cast<E>(i_), base_[i_]}; }
    constexpr entry_iterator& operator++()
    {
        ++i_;
        return *this;
    }
    constexpr entry_iterator operator++(int)
    {
        auto tmp = *this;
        ++i_;
        return tmp;
    }
    constexpr bool operator==(const entry_iterator&) const = default;
};

// The range entries() returns. Non-owning: it points into the map, so it
// dangles if the map does.
template <class E, class V> class entry_view
{
    V* base_ = nullptr;
    std::size_t n_ = 0;

  public:
    constexpr entry_view(V* base, std::size_t n) : base_(base), n_(n) {}
    constexpr auto begin() const { return entry_iterator<E, V>{base_, 0}; }
    constexpr auto end() const { return entry_iterator<E, V>{base_, n_}; }
    constexpr std::size_t size() const { return n_; }
};
} // namespace detail

// ---------------------------------------------------------------------------
// total_map
// ---------------------------------------------------------------------------
template <class E, class V> class total_map
{
    static_assert(std::is_enum_v<E>, "emap::total_map: E must be an enum type.");
    static_assert(has_enum_count<E>,
        "emap::total_map: could not determine the number of enumerators of E. Add a "
        "trailing sentinel enumerator (`Count` by default), specialize "
        "emap::enum_count<E>::value, or claim E with an emap::enum_count_policy<E>.");
    static_assert(std::is_copy_constructible_v<V>,
        "emap::total_map: V must be copy-constructible to be placed into storage.");

    static constexpr std::size_t N = enum_count_v<E>;

    // N == 0 means E was read as having no enumerators at all, which no real
    // enum has. The overwhelmingly likely cause is a `Count` enumerator that is
    // a REAL value at position 0, not a trailing sentinel — e.g.
    // `enum class Agg { Count, Sum, Avg }`, where the default trait reads
    // Count == 0 and concludes the enum is empty.
    static_assert(N > 0,
        "emap::total_map: E was read as having zero enumerators. If the sentinel being "
        "read is a real enumerator of your enum rather than a trailing sentinel, "
        "specialize emap::enum_count<E> with the true count.");

    std::array<V, N> data_; // values only — keys were dropped after validation

    // Validate exhaustiveness/uniqueness/range and return, for each enum index,
    // the input slot that holds it. A taken `throw` is not a constant
    // expression, so any violation turns this consteval evaluation into a
    // compile error.
    //
    // There is deliberately NO `M != N` check, and a wrong row count is still
    // rejected — by the checks below, which report it more precisely:
    //
    //   M < N  the missing enumerators reach the coverage loop  -> "not covered"
    //   M > N  M keys cannot be distinct in [0, N), so by pigeonhole one of the
    //          range or uniqueness checks fires first  -> "duplicate enum key"
    //
    // So the accepted set is exactly the same as with an explicit count check;
    // only the diagnostic differs, and each check now names one concept. An
    // earlier `if (M != N)` throw masked the coverage loop entirely (making it
    // unreachable), and answered a forgotten row with advice about `Count` and
    // stale counts — the trust-boundary caveat, aimed at someone who had simply
    // omitted a line.
    template <std::size_t M>
    static consteval std::array<std::size_t, N> make_perm(const std::array<entry<E, V>, M>& in)
    {
        std::array<std::size_t, N> perm{};
        std::array<bool, N> seen{};
        for (std::size_t i = 0; i < M; ++i) {
            const std::size_t idx = static_cast<std::size_t>(in[i].key);
            if (idx >= N) {
                throw "emap::total_map: enum key >= enum_count_v<E>. If that key is a real "
                      "enumerator, N is too small: is the sentinel being read a real "
                      "enumerator of your enum rather than a trailing sentinel, or has a "
                      "hand-written emap::enum_count<E> gone stale? Specialize "
                      "emap::enum_count<E>.";
            }
            if (seen[idx]) {
                throw "emap::total_map: duplicate enum key";
            }
            seen[idx] = true;
            perm[idx] = i;
        }
        for (std::size_t i = 0; i < N; ++i) {
            if (!seen[i]) {
                // Leads with the overwhelmingly common cause (a forgotten row);
                // the stale-N case is the same trust-boundary caveat the
                // out-of-range message carries, in its mirror image: N too
                // LARGE leaves a slot no row can fill. Only a hand-written
                // count can go stale this way — a sentinel, read by the default
                // rule or by a policy, tracks the enumerators by construction.
                throw "emap::total_map: enum value not covered. Some enumerator has no row. "
                      "If your table looks complete, N may be too large: has a hand-written "
                      "emap::enum_count<E> gone stale? Specialize emap::enum_count<E> with "
                      "the true count.";
            }
        }
        return perm;
    }

    // Build data_ from the permutation, copying the VALUE of each row and
    // discarding its key. V is only copy-constructed, so no default constructor
    // is required.
    template <std::size_t M, std::size_t... Is>
    consteval total_map(const std::array<entry<E, V>, M>& in, const std::array<std::size_t, N>& perm,
                        std::index_sequence<Is...>)
        : data_{in[perm[Is]].value...}
    {
    }

  public:
    // Construct from an array holding exactly one entry per enumerator, in any
    // order. consteval => the check runs at compile time on every construction.
    template <std::size_t M>
    consteval total_map(const std::array<entry<E, V>, M>& in)
        : total_map(in, make_perm(in), std::make_index_sequence<N>{})
    {
    }

    // Variadic authoring: `total_map{entry{...}, entry{...}, ...}` with no
    // std::array wrapper. Delegates to the array constructor above, so all
    // validation stays in exactly one place. The same_as constraint keeps this
    // from competing with the array overload (a std::array cannot deduce as
    // entry<E, V>) and turns a mixed-type row into a clear constraint error.
    template <std::same_as<entry<E, V>>... Rows>
    consteval total_map(Rows... rows)
        : total_map(std::array<entry<E, V>, sizeof...(Rows)>{rows...})
    {
    }

    // The key's TYPE is checked by the signature. Its VALUE is checked only in
    // debug (see CAVEATS): a `Count` sentinel used as a live "none" value, or
    // any forged cast, would otherwise read out of bounds. Free under NDEBUG,
    // and constant-expression subscripts are checked regardless.
    //
    // Mutation is safe: only the value is exposed; there is no stored key to
    // corrupt.
    constexpr const V& operator[](E e) const
    {
        assert(static_cast<std::size_t>(e) < N &&
               "emap::total_map: key out of range (a sentinel used as a live value?)");
        return data_[static_cast<std::size_t>(e)];
    }
    constexpr V& operator[](E e)
    {
        assert(static_cast<std::size_t>(e) < N &&
               "emap::total_map: key out of range (a sentinel used as a live value?)");
        return data_[static_cast<std::size_t>(e)];
    }

    // Iteration is over VALUES, in enum order. Both const and mutable, since
    // mutating a value can no longer break any invariant.
    constexpr auto begin() { return data_.begin(); }
    constexpr auto end() { return data_.end(); }
    constexpr auto begin() const { return data_.begin(); }
    constexpr auto end() const { return data_.end(); }
    constexpr auto cbegin() const { return data_.cbegin(); }
    constexpr auto cend() const { return data_.cend(); }

    constexpr V* data() { return data_.data(); }
    constexpr const V* data() const { return data_.data(); }

    static constexpr std::size_t size() { return N; }

    // Keys are not stored, but each is recoverable in O(1) from its slot, since
    // storage is indexed by static_cast<size_t>(key) and E is contiguous from 0.
    // Prefer entries() for iteration; this is the direct form for a single slot.
    // Static, so it is callable on an instance or on the type:
    //     m.key_at(i)
    //     emap::total_map<E, V>::key_at(i)   // generic code with no instance
    static constexpr E key_at(std::size_t i)
    {
        assert(i < N && "emap::total_map: index out of range");
        return static_cast<E>(i);
    }

    // Iterate keys alongside values: `for (auto [k, v] : m.entries())`.
    // Values are references, so mutation through the view works. The view is
    // non-owning — calling entries() on a temporary dangles, as with any view.
    constexpr auto entries() { return detail::entry_view<E, V>{data_.data(), N}; }
    constexpr auto entries() const { return detail::entry_view<E, const V>{data_.data(), N}; }
};

// Deduction guide: deduces E and V from the entry rows, keeping call sites
// clean. `emap::total_map m{std::array{entry{...}, ...}}` needs no factory.
template <class E, class V, std::size_t M>
total_map(const std::array<entry<E, V>, M>&) -> total_map<E, V>;

// Guide for the variadic form: E and V come from the first row; the
// constructor's same_as constraint requires the rest to match.
template <class E, class V, class... Rest>
total_map(entry<E, V>, Rest...) -> total_map<E, V>;

// ---------------------------------------------------------------------------
// Buildability predicate — a compile-time answer to "would total_map(Arr)
// succeed?". True iff the array covers every enumerator exactly once with the
// correct size; false for any table that would be rejected. This makes the
// rejection behavior expressible with static_assert.
//
// ONE concept, two ways to pass the table. Which you use is decided by what your
// V supports, not by picking a different name:
//
//   emap::buildable<Arr>    — BY VALUE; nicest syntax; limited (see below)
//   emap::buildable<&Arr>   — BY POINTER; works for ANY value type
//
// HOW IT WORKS
//   It forces the consteval construction — `total_map(...)`, CTAD on the
//   consteval constructor — into a template-argument position (the operand of
//   std::bool_constant<...>), so a `throw` from make_perm during that evaluation
//   is caught as a *substitution failure* — making the concept false — instead
//   of a hard error.
//
//   The CONSTRUCTION must be the outermost call in that operand. Only the
//   ARGUMENT may be computed by a helper (which is exactly what detail::
//   deref_if_ptr does below, and why the by-pointer form costs nothing). Routing
//   the CONSTRUCTION itself through another callable — wrapping the whole thing
//   in a lambda, say — pushes the throw out of the immediate context.
//
//   That last point is not folklore; it is measured, and IMPLEMENTATIONS
//   DISAGREE. Wrapping the construction in a lambda gives:
//       g++ 13.3    — HARD ERROR, compilation aborts
//       clang++ 22  — a clean `false`, compiles fine
//   So the rule is a real portability constraint, not a style preference: g++
//   will reject what clang accepts. Keep the construction outermost.
//
// PASSING BY VALUE — emap::buildable<Arr> (convenient, but restricted)
//   Passes the ARRAY directly as a non-type template parameter, so Arr must be a
//   valid NTTP. That is STRICTER than "the table builds": both the TYPE and the
//   VALUES must qualify.
//     * The type: entry<E,V> must be STRUCTURAL — V structural, all members
//       public and non-mutable. Plain aggregates and scalars qualify. A value
//       type with private members does NOT: e.g. total_map<E, std::string_view>
//       BUILDS fine, but `emap::buildable<array-of-string_view>` is a HARD
//       ERROR ("not structural"), not a `false`. (std::string is the same.)
//     * The values: even a structural type can hold a value that is not a valid
//       template argument. The canonical case is `const char*` initialized from
//       a string literal: `const char*` is structural, but a pointer NTTP may
//       not point at a string-literal object, so an array of such entries is
//       ALSO a hard error at the point of use.
//   Note both failures are HARD ERRORS in forming this concept-id, upstream of
//   anything this header can intercept; there is no way to turn them into a
//   friendly message here, and C++20 has no reliable way to pre-detect "is T a
//   valid NTTP type" (a would-be structural_type<T> either false-positives on
//   private-member types or false-negatives on non-default-constructible ones).
//   So: use this form for scalar/aggregate value types; for anything else pass
//   by pointer, below.
//
// PASSING BY POINTER — emap::buildable<&Arr> (general)
//   Passes a POINTER to the array. A pointer is a structural NTTP type no matter
//   what it points at, and the array is reached by dereference *inside* the
//   constant expression — so the array's own type and values never face the NTTP
//   rules. This form works for std::string_view, std::string, `const char*`
//   holding string literals, and any other buildable value type, while still
//   returning false for missing / duplicate / wrong-size tables.
//   Its ONE requirement is that &Arr be a constant expression, i.e. Arr must have
//   static storage duration: a namespace-scope constexpr (inline or not) or a
//   `static constexpr` local. A plain block-scope constexpr has automatic
//   storage and is rejected with a clear message of its own ("the address of
//   'Arr' is not a valid template argument because it does not have static
//   storage duration") — so this constraint is self-diagnosing.
//
//   Example:
//       inline constexpr auto labels = std::array{
//           emap::entry{Color::Red, std::string_view{"red"}},
//           emap::entry{Color::Green, std::string_view{"green"}},
//           emap::entry{Color::Blue, std::string_view{"blue"}}};
//       static_assert(emap::buildable<&labels>);       // OK, true
//
// TWO OTHER WAYS to make the convenient by-value form usable for string-like V
//   (if you specifically want emap::buildable<Arr> rather than the pointer
//    form), both keep V structural AND the values NTTP-valid:
//     1. Point `const char*` at NAMED objects with static storage + linkage
//        instead of inline literals:
//            inline constexpr char kRed[]="red", kGreen[]="green", kBlue[]="blue";
//            // emap::entry{Color::Red, +kRed}, ... -> valid template argument
//     2. Store the string BY VALUE in a small structural wrapper with a public
//        char[Cap] member (a fixed-capacity string), so no pointer-to-literal is
//        involved. Pick one Cap large enough for every entry (different literal
//        lengths would otherwise be different types).
// ---------------------------------------------------------------------------
namespace detail
{
// Yields the array itself, or the array a pointer points at. This computes only
// the ARGUMENT — total_map(...) stays the outermost call in the bool_constant
// operand below, which is what keeps a throw from make_perm a substitution
// failure. (Routing the CONSTRUCTION through a callable is the thing that
// breaks, and breaks differently per compiler; see the note above.)
template <class T> constexpr decltype(auto) deref_if_ptr(T x)
{
    if constexpr (std::is_pointer_v<T>) {
        return *x;
    } else {
        return x;
    }
}
} // namespace detail

template <auto X>
concept buildable =
    requires { typename std::bool_constant<(total_map(detail::deref_if_ptr(X)), true)>; };

} // namespace emap

// ============================================================================
// SELF-TESTS
// Compile-time only; they emit no runtime code. OPT-IN: define TOTAL_MAP_SELFTEST
// before including this header to compile them. Off by default so ordinary
// consumers pay nothing and get no stand-in types in scope.
//
// They ship IN the header on purpose, so you can check this library against
// YOUR compiler with a three-line TU (see tests/selftest.cpp in this repo):
//
//     #define TOTAL_MAP_SELFTEST
//     #include <emap/total_map.h>
//     int main() {}
//
//     c++ -std=c++20 -Iinclude -fsyntax-only tests/selftest.cpp
//
// A clean compile means every guarantee below holds on your toolchain. That is
// worth checking rather than assuming: the guarantees rest on consteval,
// requires, and CTAD-driven substitution failure — a corner of C++20 where
// implementations can legitimately differ.
// ============================================================================
#ifdef TOTAL_MAP_SELFTEST
#include <ranges>
#include <string_view>
// --- version macros ---
// The documented consumer gate is a PREPROCESSOR one, so TOTAL_MAP_VERSION must
// be evaluable by the preprocessor itself, not merely by the compiler proper. No
// static_assert can show that; only a real #if can, which is why this check has
// the shape it does.
#if !defined(TOTAL_MAP_VERSION) || TOTAL_MAP_VERSION < 100
#error "total_map: TOTAL_MAP_VERSION must be usable in #if and be >= 0.1.0"
#endif

namespace emap::selftest
{

// TOTAL_MAP_VERSION_STRING is DERIVED from the three components by
// stringification rather than written out, so this proves the derivation
// actually holds on YOUR preprocessor: the components are the single source of
// truth, and a consumer printing the string must see exactly the version a
// consumer gating on TOTAL_MAP_VERSION sees.
//
// It PARSES the string rather than comparing it against a second spelling —
// a literal "0.1.0" here would reintroduce exactly the drift the derivation
// removes, and would be the thing most likely to go stale in this file.
constexpr bool versionStringMatchesComponents()
{
    std::string_view s{TOTAL_MAP_VERSION_STRING};
    const std::size_t want[] = {TOTAL_MAP_VERSION_MAJOR, TOTAL_MAP_VERSION_MINOR,
                                TOTAL_MAP_VERSION_PATCH};

    for (std::size_t part = 0; part < 3; ++part) {
        const std::size_t dot = s.find('.');
        const std::string_view field = s.substr(0, dot);
        if (field.empty()) {
            return false;
        }

        std::size_t n = 0;
        for (const char c : field) {
            if (c < '0' || c > '9') {
                return false;
            }
            n = n * 10 + static_cast<std::size_t>(c - '0');
        }
        if (n != want[part]) {
            return false;
        }

        // Exactly three fields: a dot must follow all but the last, and nothing
        // may trail the last. Catches both a truncated string and stray junk.
        const bool last = (part == 2);
        if (last != (dot == std::string_view::npos)) {
            return false;
        }
        if (!last) {
            s.remove_prefix(dot + 1);
        }
    }
    return true;
}
static_assert(versionStringMatchesComponents());

// The encoding TOTAL_MAP_VERSION promises, locked so a later edit cannot quietly
// change what a consumer's `#if TOTAL_MAP_VERSION >= 10200` means.
static_assert(TOTAL_MAP_VERSION ==
              TOTAL_MAP_VERSION_MAJOR * 10000 + TOTAL_MAP_VERSION_MINOR * 100 +
                  TOTAL_MAP_VERSION_PATCH);

enum class Color { Red, Green, Blue, Count };

struct Style {
    int thickness;
    const char* name;
}; // pure payload — NO key member

// construction + lookup, with the input array in arbitrary order
constexpr emap::total_map kBasic{std::array{
    entry{Color::Blue, Style{3, "blue"}},
    entry{Color::Red, Style{1, "red"}},
    entry{Color::Green, Style{2, "green"}},
}};
static_assert(kBasic[Color::Red].thickness == 1);
static_assert(kBasic[Color::Green].thickness == 2);
static_assert(kBasic[Color::Blue].thickness == 3);
static_assert(kBasic[Color::Blue].name[0] == 'b');
static_assert(kBasic.size() == 3);

// CTAD deduces E and V from the entry rows
static_assert(std::is_same_v<decltype(kBasic), const emap::total_map<Color, Style>>);

// variadic authoring — no std::array wrapper
constexpr emap::total_map kVariadic{
    entry{Color::Blue, Style{3, "blue"}},
    entry{Color::Red, Style{1, "red"}},
    entry{Color::Green, Style{2, "green"}},
};
static_assert(std::is_same_v<decltype(kVariadic), const emap::total_map<Color, Style>>);
static_assert(kVariadic[Color::Red].thickness == 1);
static_assert(kVariadic[Color::Green].thickness == 2);
static_assert(kVariadic[Color::Blue].thickness == 3);
static_assert(kVariadic.size() == 3);

// the variadic and array forms agree
static_assert(kVariadic[Color::Green].thickness == kBasic[Color::Green].thickness);

// scalar payload is stored and read directly — no wrapper, no `.value`
constexpr emap::total_map kCost{std::array{
    entry{Color::Green, 500.0},
    entry{Color::Red, 1250.0},
    entry{Color::Blue, 625.0},
}};
static_assert(kCost[Color::Red] == 1250.0);
static_assert(kCost[Color::Green] == 500.0);
static_assert(std::is_same_v<decltype(kCost), const emap::total_map<Color, double>>);

// works with a non-default-constructible value type
struct Weight {
    int g;
    constexpr explicit Weight(int grams) : g(grams) {}
};
static_assert(!std::is_default_constructible_v<Weight>);
constexpr emap::total_map kWeights{std::array{
    entry{Color::Green, Weight{20}},
    entry{Color::Blue, Weight{30}},
    entry{Color::Red, Weight{10}},
}};
static_assert(kWeights[Color::Green].g == 20);

// mutation through the non-const accessor in a constexpr context — safe now,
// because there is no stored key to desynchronize.
constexpr int mutated()
{
    emap::total_map m{std::array{
        entry{Color::Red, Style{1, "red"}},
        entry{Color::Green, Style{2, "green"}},
        entry{Color::Blue, Style{3, "blue"}},
    }};
    m[Color::Blue].thickness = 99;
    return m[Color::Blue].thickness;
}
static_assert(mutated() == 99);

// Values iterate in enum order (by key), regardless of authoring order. key_at
// recovers each key from its position, so mutating a value cannot ever make an
// element disagree with its slot (the old failure mode is gone by construction).
constexpr bool iteratesInEnumOrder()
{
    std::size_t i = 0;
    for (const auto& v : kBasic) {
        // slot i must correspond to enum value i; check via the recovered key
        if (emap::total_map<Color, Style>::key_at(i) != static_cast<Color>(i)) {
            return false;
        }
        // and the value at that slot is the one authored for that key
        if (kBasic[static_cast<Color>(i)].thickness != v.thickness) {
            return false;
        }
        ++i;
    }
    return i == kBasic.size();
}
static_assert(iteratesInEnumOrder());

// key_at is callable ON AN INSTANCE as well as on the type — a static member can
// be called through an object. The docs promise `m.key_at(i)`, so lock both
// spellings rather than only the qualified one used above.
static_assert(kBasic.key_at(0) == Color::Red);
static_assert(kBasic.key_at(1) == Color::Green);
static_assert(kBasic.key_at(2) == Color::Blue);
static_assert(emap::total_map<Color, Style>::key_at(0) == Color::Red);

// --- entries(): iterate keys alongside values ---
// The no-stored-keys design should be invisible here.
constexpr bool entriesAreInEnumOrder()
{
    std::size_t i = 0;
    for (auto [key, value] : kBasic.entries()) {
        if (key != static_cast<Color>(i)) {
            return false;
        }
        if (value.thickness != kBasic[key].thickness) {
            return false;
        }
        ++i;
    }
    return i == kBasic.size();
}
static_assert(entriesAreInEnumOrder());

// mutation through entries(), in a constant expression
constexpr int mutateViaEntries()
{
    emap::total_map m{
        entry{Color::Red, Style{1, "red"}},
        entry{Color::Green, Style{2, "green"}},
        entry{Color::Blue, Style{3, "blue"}},
    };
    for (auto [key, value] : m.entries()) {
        value.thickness *= 10;
    }
    return m[Color::Blue].thickness;
}
static_assert(mutateViaEntries() == 30);

// The iterator models forward_iterator in both const and mutable forms, and the
// view is a forward_range. Asserted so a later edit cannot silently downgrade
// it and break composition with std::views for consumers.
static_assert(std::forward_iterator<emap::detail::entry_iterator<Color, Style>>);
static_assert(std::forward_iterator<emap::detail::entry_iterator<Color, const Style>>);
static_assert(std::ranges::forward_range<emap::detail::entry_view<Color, const Style>>);

// entry_ref converts to entry — this is what keeps the iterator's value_type
// honest, and it is why a bare aggregate could not be used here.
static_assert(std::convertible_to<emap::entry_ref<Color, const Style>, emap::entry<Color, Style>>);

// named members (.key/.value), not std::pair's .first/.second
constexpr bool entryRefHasNamedMembers()
{
    for (auto e : kBasic.entries()) {
        if (e.key == Color::Green) {
            return e.value.thickness == 2;
        }
    }
    return false;
}
static_assert(entryRefHasNamedMembers());

// entries() actually composes with std::views — not merely modelling
// forward_range, but surviving a real pipe. This header does not include
// <ranges>; the self-test block above does, which is exactly the consumer's
// position. Red (thickness 1) must be filtered out.
constexpr bool entriesComposeWithViews()
{
    int total = 0;
    for (auto [key, value] :
         kBasic.entries() | std::views::filter([](auto e) { return e.value.thickness > 1; })) {
        if (key == Color::Red) {
            return false; // Red should have been filtered out
        }
        total += value.thickness;
    }
    return total == 5; // green(2) + blue(3)
}
static_assert(entriesComposeWithViews());

// enum_count customization: an enum with no Count sentinel
enum class Dir { North, East, South, West };

} // namespace emap::selftest

namespace emap
{
template <> struct enum_count<selftest::Dir> : std::integral_constant<std::size_t, 4> {
};
}

namespace emap::selftest
{
constexpr emap::total_map kDirs{std::array{
    entry{Dir::North, 0},
    entry{Dir::East, 90},
    entry{Dir::South, 180},
    entry{Dir::West, 270},
}};
static_assert(kDirs[Dir::West] == 270);
static_assert(kDirs.size() == 4);

// --- rejection behavior, expressed as static_assert via emap::buildable ---
// (entry<Color,int> is structural, so its arrays are valid template params.)
constexpr auto kComplete =
    std::array{entry{Color::Red, 1}, entry{Color::Green, 2}, entry{Color::Blue, 3}};
constexpr auto kMissing = std::array{entry{Color::Red, 1}, entry{Color::Green, 2}}; // no Blue
constexpr auto kDuplicate =
    std::array{entry{Color::Red, 1}, entry{Color::Red, 2}, entry{Color::Blue, 3}}; // dup Red
constexpr auto kOversized = std::array{entry{Color::Red, 1}, entry{Color::Green, 2},
                                       entry{Color::Blue, 3}, entry{Color::Red, 4}};
static_assert(emap::buildable<kComplete>);
static_assert(!emap::buildable<kMissing>);
static_assert(!emap::buildable<kDuplicate>);
static_assert(!emap::buildable<kOversized>);

// --- reach of the BY-VALUE predicate, and the BY-POINTER escape hatch ---
// A const char* value holding a string literal builds fine as a table, but the
// by-value emap::buildable<...> cannot be formed on it (the literal pointer
// is not a valid template argument). The by-pointer form handles it, because the
// array is reached by dereference and never itself becomes a template argument.
constexpr emap::total_map kLabelled{std::array{
    entry{Color::Red, "red"},
    entry{Color::Green, "green"},
    entry{Color::Blue, "blue"},
}};
static_assert(kLabelled[Color::Blue][0] == 'b');
static_assert(std::is_same_v<decltype(kLabelled), const emap::total_map<Color, const char*>>);

// const char* literals: unreachable by value, reachable by pointer.
inline constexpr auto kLit = std::array{
    entry{Color::Red, "red"}, entry{Color::Green, "green"}, entry{Color::Blue, "blue"}};
inline constexpr auto kLitBad = std::array{ // duplicate Red
    entry{Color::Red, "red"}, entry{Color::Red, "x"}, entry{Color::Blue, "blue"}};
static_assert(emap::buildable<&kLit>);
static_assert(!emap::buildable<&kLitBad>);

// std::string_view: non-structural, so unreachable by value; reachable by ptr.
inline constexpr auto kSV = std::array{
    entry{Color::Red, std::string_view{"red"}},
    entry{Color::Green, std::string_view{"green"}},
    entry{Color::Blue, std::string_view{"blue"}}};
inline constexpr auto kSVBad = std::array{ // missing Blue
    entry{Color::Red, std::string_view{"red"}}, entry{Color::Green, std::string_view{"green"}}};
static_assert(emap::buildable<&kSV>);
static_assert(!emap::buildable<&kSVBad>);

// the by-pointer form agrees with the by-value form on structural tables too
static_assert(emap::buildable<&kComplete>);
static_assert(!emap::buildable<&kMissing>);

// --- `Count` colliding with a REAL enumerator ---
// The default trait guesses N from a trailing `Count`. When `Count` is a real
// value the guess is wrong. These lock in exactly what that costs — including
// the part that is NOT caught. See "THE ONE THING IT DOES NOT PROVE" at the top.
enum class Metric { Sum, Count, Mean, Max }; // Count is a statistic, not a sentinel

// The guess is wrong: N reads as 1, not 4.
static_assert(emap::enum_count_v<Metric> == 1);

// Authoring the real enumerators is REJECTED — the usual, loud outcome. The
// diagnostics name this exact suspicion. buildable expresses it without a hard
// error.
constexpr auto kMetricsAll = std::array{entry{Metric::Sum, 1.0}, entry{Metric::Count, 2.0},
                                        entry{Metric::Mean, 3.0}, entry{Metric::Max, 4.0}};
static_assert(!emap::buildable<kMetricsAll>);

// But a table covering exactly 0..N-1 is ACCEPTED, silently leaving Mean and Max
// uncovered. This is the hole, asserted rather than hidden: if a future change
// makes this false, the trust boundary moved and the docs above must be redone.
constexpr auto kMetricsFirstOnly = std::array{entry{Metric::Sum, 1.0}};
static_assert(emap::buildable<kMetricsFirstOnly>);

// The escape hatch resolves it — but the specialization must appear BEFORE the
// enum's first use with total_map. A trait cannot be specialized after it has
// been implicitly instantiated, so `Metric` above is now permanently stuck with
// the wrong N; a separate enum is needed to show the fix.
enum class Stat { Sum, Count, Mean, Max }; // same shape, specialized before use
} // namespace emap::selftest

namespace emap
{
template <> struct enum_count<selftest::Stat> : std::integral_constant<std::size_t, 4> {
};
}

namespace emap::selftest
{
static_assert(emap::enum_count_v<Stat> == 4);
constexpr auto kStatsAll = std::array{entry{Stat::Sum, 1.0}, entry{Stat::Count, 2.0},
                                      entry{Stat::Mean, 3.0}, entry{Stat::Max, 4.0}};
constexpr auto kStatsPartial = std::array{entry{Stat::Sum, 1.0}};
static_assert(emap::buildable<kStatsAll>);      // the full table now builds
static_assert(!emap::buildable<kStatsPartial>); // and a partial one is caught again
constexpr emap::total_map kStats{kStatsAll};
static_assert(kStats[Stat::Max] == 4.0);
static_assert(kStats[Stat::Count] == 2.0); // `Count` is a real key, and works
static_assert(kStats.size() == 4);
} // namespace emap::selftest

// --- enum_count_policy: a project-wide sentinel rule ---
// A consumer whose house sentinel is not `Count` writes ONE block like this, in
// one header, and every enum in the project follows. No per-enum annotation, no
// macro, no build-time configuration.
//
// This test keys on `SelftestCount`, not on a plausible spelling like `Size`,
// deliberately: a policy is a RULE and reaches every enum in the TU, so a
// realistic spelling here would claim a consumer's own enums in any TU that
// defines TOTAL_MAP_SELFTEST. See "no stand-in types in scope" above.
namespace emap
{
template <class E>
    requires (std::is_enum_v<E> && requires { E::SelftestCount; })
struct enum_count_policy<E>
    : std::integral_constant<std::size_t, static_cast<std::size_t>(E::SelftestCount)> {
};
}

namespace emap::selftest
{
// The policy claims this enum: no `Count`, no specialization, nothing per-enum.
enum class Hue { Red, Green, Blue, SelftestCount };
static_assert(emap::enum_count_v<Hue> == 3);
constexpr emap::total_map kHues{
    entry{Hue::Red, 1}, entry{Hue::Green, 2}, entry{Hue::Blue, 3}};
static_assert(kHues[Hue::Green] == 2);
static_assert(kHues.size() == 3);

// BOTH spellings present. The policy outranks the stock `Count` rule, so this
// resolves to 4 with no annotation — and, crucially, is NOT an ambiguous partial
// specialization. Without the `!has_count_policy` term on the stock rule this
// line is a hard error that no static_assert can intercept.
enum class Gauge { Sum, Count, Mean, Max, SelftestCount };
static_assert(emap::enum_count_v<Gauge> == 4);
constexpr emap::total_map kGauge{
    entry{Gauge::Sum, 1.0}, entry{Gauge::Count, 2.0},
    entry{Gauge::Mean, 3.0}, entry{Gauge::Max, 4.0}};
static_assert(kGauge[Gauge::Count] == 2.0); // `Count` is a real key, and works
static_assert(kGauge.size() == 4);

// A policy is ADDITIVE: an enum still using the stock `Count` sentinel keeps
// working alongside it. This is the property a build-wide sentinel macro could
// not have — it would have removed `Count` recognition for the whole build.
enum class Tone { Soft, Loud, Count };
static_assert(emap::enum_count_v<Tone> == 2);

// Neither rule claims it -> a clean false, so the friendly static_assert in
// total_map still fires rather than an incomplete-type error.
enum class Bare { A, B };
static_assert(!emap::has_enum_count<Bare>);
static_assert(!emap::has_enum_count<int>); // non-enum, still clean

// An explicit specialization outranks BOTH tiers (declared below, before use).
enum class Odd { A, Count, SelftestCount, B };

// One enum spelling its own sentinel, where no policy names it. The
// specialization READS that sentinel rather than hardcoding a number, so it
// self-maintains: add an enumerator and N follows. This is the form to reach
// for when sentinels vary per enum (NUM_COLORS, kDirCount) — no single policy
// can name them.
enum class Lane { Left, Right, LaneCount };
} // namespace emap::selftest

namespace emap
{
template <> struct enum_count<selftest::Odd> : std::integral_constant<std::size_t, 4> {
};

// The static_cast is required: integral_constant's second argument is a
// std::size_t and a scoped enum does not convert to one implicitly.
template <> struct enum_count<selftest::Lane>
    : std::integral_constant<std::size_t, static_cast<std::size_t>(selftest::Lane::LaneCount)> {
};
}

namespace emap::selftest
{
static_assert(emap::enum_count_v<Odd> == 4);

static_assert(emap::enum_count_v<Lane> == 2);
constexpr emap::total_map kLanes{entry{Lane::Left, 'L'}, entry{Lane::Right, 'R'}};
static_assert(kLanes[Lane::Right] == 'R');
static_assert(kLanes.size() == 2);
// The sentinel is not a key: a table trying to cover it is rejected.
constexpr auto kLanesBad =
    std::array{entry{Lane::Left, 'L'}, entry{Lane::Right, 'R'}, entry{Lane::LaneCount, 'X'}};
static_assert(!emap::buildable<kLanesBad>);
} // namespace emap::selftest
#endif // TOTAL_MAP_SELFTEST

// ============================================================================
// MUST-NOT-COMPILE TESTS
// For a structural V, prefer emap::buildable<Arr> above — it expresses the same
// rejection behavior as an ordinary static_assert. This out-of-line driver
// covers the two cases buildable cannot reach:
//
//   1. Non-structural V (std::string_view, ...), where the table cannot be
//      named as a template parameter at all — direct construction is a hard
//      error that aborts the TU, so it cannot be caught by a concept.
//   2. THE VARIADIC FORM. buildable only takes an array, so nothing above can
//      assert that `total_map{entry{...}, entry{...}}` rejects a bad table. The
//      variadic constructor delegates to the array constructor precisely so
//      validation stays in one place; these checks are what prove it still does.
//      Without them, a variadic ctor that skipped make_perm would pass every
//      other test in this header.
//
// Verify each snippet FAILS to compile. Example driver (bash):
//
//   preamble='#include <emap/total_map.h>
//   enum class Color{Red,Green,Blue,Count};'
//
//   check() {  # $1 = rows expected to be rejected (array form OR variadic)
//     printf '%s\nconstexpr emap::total_map m{%s}; int main(){}\n' "$preamble" "$1" > t.cpp
//     g++ -std=c++20 -Iinclude -fsyntax-only t.cpp 2>/dev/null && echo "BUG: compiled" || echo "OK: rejected"
//   }
//
//   # --- array form ---
//   check 'std::array{emap::entry{Color::Red,1},emap::entry{Color::Green,2}}'                                        # missing Blue
//   check 'std::array{emap::entry{Color::Red,1},emap::entry{Color::Red,2},emap::entry{Color::Blue,3}}'               # duplicate Red
//   check 'std::array{emap::entry{Color::Red,1},emap::entry{Color::Green,2},emap::entry{Color::Blue,3},emap::entry{Color::Red,4}}' # size
//
//   # --- variadic form: same guarantees, different construction path ---
//   check 'emap::entry{Color::Red,1},emap::entry{Color::Green,2}'                                        # missing Blue
//   check 'emap::entry{Color::Red,1},emap::entry{Color::Red,2},emap::entry{Color::Blue,3}'               # duplicate Red
//   check 'emap::entry{Color::Red,1},emap::entry{Color::Green,2},emap::entry{Color::Blue,3},emap::entry{Color::Red,4}' # size
//
//   # --- positive controls: these MUST compile, or the driver proves nothing ---
//   check_ok() {
//     printf '%s\nconstexpr emap::total_map m{%s}; int main(){}\n' "$preamble" "$1" > t_ok.cpp
//     g++ -std=c++20 -fsyntax-only t_ok.cpp && echo "OK: complete table compiles" || echo "BUG: rejected a valid table"
//   }
//   check_ok 'std::array{emap::entry{Color::Red,1},emap::entry{Color::Green,2},emap::entry{Color::Blue,3}}'
//   check_ok 'emap::entry{Color::Red,1},emap::entry{Color::Green,2},emap::entry{Color::Blue,3}'
// ============================================================================

#endif // TOTAL_MAP_INCLUDED
